-- seed_resources.sql — curated resource matrix for the coach agent.
--
-- Generated from the hand-curated link list (July 2026). internal_drill
-- URLs point at the existing /{skill}/practice?type=<question_type> flow.
-- Instructions are in English: they are INPUT for the AI formulator, which
-- rewrites them in the user's language — not shown to users verbatim.
--
-- Re-runnable as the source of truth: upsert on (module, problem_tag, title),
-- so editing a row here and re-running the whole file updates live rows.

insert into resources (module, problem_tag, resource_type, title, url, instruction) values

-- ── Listening ───────────────────────────────────────────────────────────
('listening', 'accents', 'video', 'British Council — Audio Zone (речь носителей из разных стран)',
 'https://learnenglish.britishcouncil.org/general-english/audio-zone',
 'Rotate accents 5-10 min/day. Goal: stop "translating" the accent and just follow the meaning.'),
('listening', 'accents', 'video', 'British vs American accent challenge (British Council Teens)',
 'https://learnenglishteens.britishcouncil.org/study-break/youtubers/british-vs-american-accent-challenge',
 'Rotate accents 5-10 min/day. Goal: stop "translating" the accent and just follow the meaning.'),
('listening', 'accents', 'guide', 'IELTS Academic — English accents in Listening',
 'https://ielts-academic.com/2015/10/31/ielts-listening-english-accents/',
 'Rotate accents 5-10 min/day. Goal: stop "translating" the accent and just follow the meaning.'),
('listening', 'accents', 'guide', 'IELTS Zone — Listening with different accents',
 'https://ieltszone.org/ielts-listening/listening-with-different-accents/',
 'Rotate accents 5-10 min/day. Goal: stop "translating" the accent and just follow the meaning.'),
('listening', 'accents', 'guide', 'Magoosh — Accents to expect in IELTS Listening',
 'https://magoosh.com/ielts/accents-expect-ielts-listening/',
 'Rotate accents 5-10 min/day. Goal: stop "translating" the accent and just follow the meaning.'),
('listening', 'form_completion', 'internal_drill', 'Form completion drill',
 '/listening/practice?type=form_completion',
 'Focus on numbers, names and spelling — that is where form questions lose points.'),
('listening', 'general_plateau', 'podcast', 'BBC 6 Minute English',
 'https://www.bbc.co.uk/learningenglish/features/6-minute-english',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'video', 'BBC Learning English (YouTube)',
 'https://www.youtube.com/@bbclearningenglish',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'podcast', 'British Council LearnEnglish — Podcasts',
 'https://learnenglish.britishcouncil.org/general-english/podcasts',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'podcast', 'Leonardo English — English Learning for Curious Minds (транскрипты)',
 'https://www.leonardoenglish.com/free-transcripts',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'podcast', 'Luke''s English Podcast',
 'https://teacherluke.co.uk/',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'podcast', 'Plain English Podcast',
 'https://plainenglish.com/english-learning-podcast/',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'ted', 'TED-Ed — How do vaccines work? (Kelwalin Dhanasarnsombut)',
 'https://ed.ted.com/lessons/how-do-vaccines-work-kelwalin-dhanasarnsombut',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'ted', 'TED-Ed — Lessons Worth Sharing (каталог коротких роликов)',
 'https://ed.ted.com/lessons',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'general_plateau', 'ted', 'TED-Ed — Why do we dream? (Amy Adkins)',
 'https://ed.ted.com/lessons/why-do-we-dream-amy-adkins',
 'Listen 10 min/day without subtitles. Catch the gist first, replay for detail; note 3 phrases you heard but would not have written.'),
('listening', 'map_labelling', 'internal_drill', 'Map labelling drill',
 '/listening/practice?type=map_labelling',
 'Before the audio starts, read the map aloud mentally: left/right, across from, next to.'),
('listening', 'matching', 'internal_drill', 'Matching drill (listening)',
 '/listening/practice?type=matching',
 'Read all options before the audio; cross out used letters as you go.'),
('listening', 'multiple_choice', 'internal_drill', 'Multiple choice drill (listening)',
 '/listening/practice?type=multiple_choice',
 'The recording will mention several options — listen for the correction ("actually", "but").'),
('listening', 'note_completion', 'internal_drill', 'Note completion drill',
 '/listening/practice?type=note_completion',
 'Timed drill on your weakest type. Before the audio: predict the word type (noun? number?) for each gap.'),
('listening', 'part3_discussion', 'ted', 'Celeste Headlee — 10 ways to have a better conversation',
 'https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation',
 'Listen for WHO says WHAT, not every word. Afterwards write one line per speaker''s position.'),
('listening', 'part3_discussion', 'ted', 'TED debate — Does the world need nuclear energy? (два спикера)',
 'https://www.ted.com/talks/debate_does_the_world_need_nuclear_energy',
 'Listen for WHO says WHAT, not every word. Afterwards write one line per speaker''s position.'),
('listening', 'part3_discussion', 'ted', 'TED playlist — Talks to support a healthy debate',
 'https://www.ted.com/playlists/482/talks_to_support_a_healthy_debate',
 'Listen for WHO says WHAT, not every word. Afterwards write one line per speaker''s position.'),
('listening', 'part3_discussion', 'ted', 'TED playlist — The art of meaningful conversation',
 'https://www.ted.com/playlists/211/the_art_of_meaningful_conversa',
 'Listen for WHO says WHAT, not every word. Afterwards write one line per speaker''s position.'),
('listening', 'part3_discussion', 'ted', 'The TED Interview (серия диалогов)',
 'https://www.ted.com/series/the-ted-interview',
 'Listen for WHO says WHAT, not every word. Afterwards write one line per speaker''s position.'),

-- ── Reading ─────────────────────────────────────────────────────────────
('reading', 'fill_blank', 'internal_drill', 'Gap fill drill (reading)',
 '/reading/practice?type=fill_blank',
 'Read around the gap first — grammar tells you the word type before you scan for it.'),
('reading', 'general_plateau', 'article', '50 Best Aeon Essays (подборка)',
 'https://tetw.org/Aeon',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'Aeon — Essays',
 'https://aeon.co/essays',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'Aeon — Popular',
 'https://aeon.co/popular',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'BBC Future (лонгриды: наука/культура)',
 'https://www.bbc.com/future',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'National Geographic',
 'https://www.nationalgeographic.com/',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'Smithsonian Magazine',
 'https://www.smithsonianmag.com/',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'general_plateau', 'article', 'The Guardian — The long read',
 'https://www.theguardian.com/news/series/the-long-read',
 'One article a day + 5 new words with example sentences. Alternate topics you would normally avoid.'),
('reading', 'matching', 'internal_drill', 'Matching drill (reading)',
 '/reading/practice?type=matching',
 'Do NOT read paragraphs in order — scan for the option''s keywords and their synonyms.'),
('reading', 'multiple_choice', 'internal_drill', 'Multiple choice drill (reading)',
 '/reading/practice?type=multiple_choice',
 'Eliminate two options by contradiction before choosing between the last two.'),
('reading', 'skimming', 'guide', 'British Council — Skimming vs Scanning for IELTS Reading',
 'https://takeielts.britishcouncil.org/blog/skimming-and-scanning-for-ielts-reading',
 'Practice the technique: 2 minutes per passage — title, first/last sentence of each paragraph, then say the topic aloud.'),
('reading', 'skimming', 'guide', 'Cambridge English — Skimming and scanning',
 'https://www.cambridge.org/elt/blog/2015/02/04/help-ielts-5-skimming-scanning/',
 'Practice the technique: 2 minutes per passage — title, first/last sentence of each paragraph, then say the topic aloud.'),
('reading', 'skimming', 'guide', 'IDP — How to skim and scan for keywords',
 'https://ielts.idp.com/prepare/article-how-to-skim-scan-for-keywords',
 'Practice the technique: 2 minutes per passage — title, first/last sentence of each paragraph, then say the topic aloud.'),
('reading', 'skimming', 'guide', 'IELTS-up — Skimming and scanning: get band 9',
 'https://ielts-up.com/reading/skimming-scanning.html',
 'Practice the technique: 2 minutes per passage — title, first/last sentence of each paragraph, then say the topic aloud.'),
('reading', 'skimming', 'guide', 'My IELTS Classroom — How to read faster',
 'https://blog.myieltsclassroom.com/how-to-read-faster/',
 'Practice the technique: 2 minutes per passage — title, first/last sentence of each paragraph, then say the topic aloud.'),
('reading', 'true_false', 'internal_drill', 'True/False/Not Given drill',
 '/reading/practice?type=true_false',
 'The trap is FALSE vs NOT GIVEN: FALSE contradicts the text, NOT GIVEN is absent from it. Verbalize which one and why.'),

-- ── Writing ─────────────────────────────────────────────────────────────
('writing', 'general_plateau', 'guide', 'IELTS Advantage — 100 band 7/8/9 sample essays',
 'https://www.ieltsadvantage.com/2023/01/15/ielts-writing-task-2-sample-essays/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'guide', 'IELTS Advantage — Writing Task 1 guide',
 'https://www.ieltsadvantage.com/writing-task-1/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'guide', 'IELTS Liz — Band 9 sample essay with model answer',
 'https://ieltsliz.com/ielts-sample-essay/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'guide', 'IELTS Liz — Linking words for writing',
 'https://ieltsliz.com/linking-words-for-writing/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'podcast', 'IELTS Podcast — 35 band 9 sample essays',
 'https://www.ieltspodcast.com/writing-task-2/band-9-sample-essays/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'podcast', 'IELTS Podcast — Band 8 vs Band 6.5 (разбор)',
 'https://www.ieltspodcast.com/writing-task-2/band-8-vs-6-5/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'general_plateau', 'guide', 'IELTS Simon — Model essays (Task 2)',
 'https://ielts-simon.study/category/ielts-writing-task-2/model-essays/',
 'Read one high-band essay per day. Copy its paragraph skeleton, then write your own essay into the same skeleton.'),
('writing', 'task_structure', 'guide', 'IELTS Advantage — Task 2 essay structures + band 9',
 'https://www.ieltsadvantage.com/2015/03/03/ielts-writing-task-2-essay-structures/',
 'One position, two body paragraphs, one idea each, developed fully. Depth beats breadth.'),
('writing', 'task_structure', 'guide', 'IELTS Jacky — Understand the 5 essay types',
 'https://www.ieltsjacky.com/ielts-task-2.html',
 'One position, two body paragraphs, one idea each, developed fully. Depth beats breadth.'),
('writing', 'task_structure', 'guide', 'IELTS Liz — Discussion essay model & structure',
 'https://ieltsliz.com/ielts-discussion-essay-model-answer/',
 'One position, two body paragraphs, one idea each, developed fully. Depth beats breadth.'),
('writing', 'task_structure', 'guide', 'IELTS Writing Analytics — Task 2 templates',
 'https://ieltswritinganalytics.com/en/ielts-writing-task-2-templates',
 'One position, two body paragraphs, one idea each, developed fully. Depth beats breadth.'),
('writing', 'task_structure', 'guide', 'Magoosh — Task 2 question types (все 5)',
 'https://magoosh.com/ielts/ielts-writing-task-2-question-types/',
 'One position, two body paragraphs, one idea each, developed fully. Depth beats breadth.'),

-- ── Speaking ────────────────────────────────────────────────────────────
('speaking', 'fluency', 'video', 'Connected Speech — Complete Master Class (YouTube)',
 'https://www.youtube.com/watch?v=Nbp--6rPq0Q',
 'Shadow a 1-2 min native clip daily: play, repeat aloud in sync, match the rhythm, ignore mistakes.'),
('speaking', 'fluency', 'video', 'How To Use The Shadowing Technique (YouTube)',
 'https://www.youtube.com/watch?v=7hsWoGgF2No',
 'Shadow a 1-2 min native clip daily: play, repeat aloud in sync, match the rhythm, ignore mistakes.'),
('speaking', 'fluency', 'guide', 'IELTS Advantage — Idioms for IELTS Speaking',
 'https://www.ieltsadvantage.com/idioms-for-ielts-speaking/',
 'Shadow a 1-2 min native clip daily: play, repeat aloud in sync, match the rhythm, ignore mistakes.'),
('speaking', 'fluency', 'guide', 'Rachel''s English — Intonation',
 'https://rachelsenglish.com/intonation/',
 'Shadow a 1-2 min native clip daily: play, repeat aloud in sync, match the rhythm, ignore mistakes.'),
('speaking', 'general_plateau', 'guide', 'IELTS Advantage — Speaking Part 1 band 9 examples',
 'https://www.ieltsadvantage.com/master-ielts-speaking-part-1-learn-from-band-9-examples/',
 'Structure the 2 minutes: what → details → why it matters → one story. Record yourself once a day.'),
('speaking', 'general_plateau', 'guide', 'IELTS Advantage — Speaking Part 2 (long turn) framework',
 'https://www.ieltsadvantage.com/ielts-speaking-part-2/',
 'Structure the 2 minutes: what → details → why it matters → one story. Record yourself once a day.'),
('speaking', 'general_plateau', 'guide', 'SpeakPrac — Speaking Part 3 complete band 9 guide',
 'https://speakprac.com/ielts-speaking-tips/part-3-complete-guide/',
 'Structure the 2 minutes: what → details → why it matters → one story. Record yourself once a day.'),

-- ── Vocabulary ──────────────────────────────────────────────────────────
('vocabulary', 'weak_vocab', 'internal_drill', 'Vocabulary decks (spaced repetition)',
 '/vocabulary',
 'Ten minutes daily beats an hour weekly — the review queue does the scheduling for you.')

on conflict (module, problem_tag, title) do update set
  url           = excluded.url,
  instruction   = excluded.instruction,
  resource_type = excluded.resource_type,
  is_active     = true;
