import { LegalPage } from '@/components/sections/LegalPage'

export const metadata = { title: 'Terms of Service · ielts.camp' }

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="2 June 2026"
      intro="These Terms of Service govern your access to and use of IELTS Camp. By creating an account, accessing the platform, or using any of our services, you agree to be bound by these Terms."
      sections={[
        {
          heading: 'Acceptance of Terms',
          body: (
            <>
              By accessing or using IELTS Camp ("IELTS Camp", "we", "our", or
              "us"), you agree to comply with these Terms of Service and all
              applicable laws and regulations. If you do not agree with these
              Terms, you must not access or use the platform.
            </>
          ),
        },
        {
          heading: 'Eligibility',
          body: (
            <>
              You must be legally capable of entering into a binding agreement
              in your jurisdiction to use the Services. If you are under the age
              of majority in your jurisdiction, you may use the Services only
              with the involvement and consent of a parent or legal guardian.
            </>
          ),
        },
        {
          heading: 'Account Registration',
          body: (
            <>
              To access certain features, you may be required to create an
              account. You agree to provide accurate and complete information and
              to keep your account information updated. You are responsible for
              maintaining the confidentiality of your login credentials and for
              all activity occurring under your account.
            </>
          ),
        },
        {
          heading: 'Educational Purpose Only',
          body: (
            <>
              IELTS Camp provides educational tools, practice materials,
              analytics, and AI-generated feedback intended to assist users in
              preparing for IELTS examinations. The platform does not provide
              official IELTS certification, examination results, immigration
              advice, legal advice, or academic guarantees.
              <br />
              <br />
              Any band scores, score estimates, recommendations, or feedback
              generated by the platform are informational only and should not be
              considered official examination results.
            </>
          ),
        },
        {
          heading: 'AI-Powered Features',
          body: (
            <>
              Certain features of the platform use artificial intelligence to
              generate writing evaluations, speaking assessments, study
              recommendations, and educational feedback.
              <br />
              <br />
              While we strive to provide useful and accurate feedback, AI
              systems may occasionally produce incomplete, inaccurate, or
              unexpected outputs. Users should independently evaluate all
              recommendations before relying on them.
            </>
          ),
        },
        {
          heading: 'Subscriptions and Billing',
          body: (
            <>
              Certain Services require a paid subscription. Subscription
              purchases are processed by Paddle, our Merchant of Record.
              <br />
              <br />
              By purchasing a subscription, you authorize Paddle to charge the
              applicable fees, taxes, and recurring subscription charges
              according to the selected billing plan.
              <br />
              <br />
              Subscription plans may be offered on a monthly, quarterly, or
              annual basis. Subscription fees are billed in advance and are
              subject to applicable taxes.
            </>
          ),
        },
        {
          heading: 'Free Trials',
          body: (
            <>
              We may offer free trials or promotional access periods. At the end
              of a trial period, access to premium features may be restricted
              unless a valid subscription is purchased.
              <br />
              <br />
              We reserve the right to modify, limit, or discontinue free trial
              offers at any time.
            </>
          ),
        },
        {
          heading: 'Cancellation and Renewal',
          body: (
            <>
              Unless canceled, subscriptions automatically renew at the end of
              each billing cycle. Users may cancel their subscriptions through
              the billing portal provided by Paddle.
              <br />
              <br />
              Cancellation prevents future renewals but does not typically
              result in a refund for the current billing period unless required
              by applicable law or our Refund Policy.
            </>
          ),
        },
        {
          heading: 'Acceptable Use',
          body: (
            <>
              You agree not to:
              <ul className="list-disc pl-6 mt-3 space-y-2">
                <li>Use the Services for unlawful purposes.</li>
                <li>Attempt to gain unauthorized access to systems or data.</li>
                <li>Share or resell your account access.</li>
                <li>Reverse engineer or copy proprietary platform features.</li>
                <li>Upload malicious software or harmful content.</li>
                <li>
                  Interfere with the security, availability, or performance of
                  the Services.
                </li>
                <li>
                  Use automated tools to scrape, harvest, or extract content
                  from the platform without permission.
                </li>
              </ul>
            </>
          ),
        },
        {
          heading: 'User Content',
          body: (
            <>
              You retain ownership of content you submit to the platform,
              including essays, responses, recordings, and study materials.
              <br />
              <br />
              By submitting content, you grant IELTS Camp a limited,
              non-exclusive license to process, store, analyze, and display such
              content solely for the purpose of providing the Services.
            </>
          ),
        },
        {
          heading: 'Intellectual Property',
          body: (
            <>
              The platform, including its software, designs, branding, logos,
              educational materials, features, and content, is owned by IELTS
              Camp or its licensors and is protected by applicable intellectual
              property laws.
              <br />
              <br />
              Except as expressly permitted, users may not reproduce,
              distribute, modify, sell, or create derivative works based on the
              Services.
            </>
          ),
        },
        {
          heading: 'Account Suspension and Termination',
          body: (
            <>
              We reserve the right to suspend, restrict, or terminate accounts
              that violate these Terms, engage in fraudulent activity, abuse the
              platform, or create security risks.
              <br />
              <br />
              We may also discontinue or modify portions of the Services at any
              time without liability.
            </>
          ),
        },
        {
          heading: 'Disclaimer of Warranties',
          body: (
            <>
              The Services are provided on an "as is" and "as available" basis.
              To the maximum extent permitted by law, IELTS Camp disclaims all
              warranties, whether express or implied, including warranties of
              merchantability, fitness for a particular purpose, accuracy,
              availability, and non-infringement.
            </>
          ),
        },
        {
          heading: 'Limitation of Liability',
          body: (
            <>
              To the fullest extent permitted by law, IELTS Camp shall not be
              liable for any indirect, incidental, consequential, special, or
              punitive damages arising from or relating to your use of the
              Services.
              <br />
              <br />
              Our total liability for any claim relating to the Services shall
              not exceed the amount paid by you to IELTS Camp during the twelve
              (12) months preceding the event giving rise to the claim.
            </>
          ),
        },
        {
          heading: 'Privacy',
          body: (
            <>
              Your use of the Services is also governed by our Privacy Policy,
              which explains how we collect, use, and protect personal
              information.
            </>
          ),
        },
        {
          heading: 'Changes to the Terms',
          body: (
            <>
              We may update these Terms from time to time. Updated versions will
              be posted on this page with a revised effective date. Continued
              use of the Services after changes become effective constitutes
              acceptance of the revised Terms.
            </>
          ),
        },
        {
          heading: 'Contact Information',
          body: (
            <>
              Questions regarding these Terms may be submitted through our
              support channels or by contacting us at support@ielts.camp.
            </>
          ),
        },
      ]}
    />
  )
}