import { LegalPage } from '@/components/sections/LegalPage'

export const metadata = { title: 'Terms of Service · ielts.camp' }

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="29 May 2026"
      intro="These terms govern your use of ielts.camp. By creating an account or using the service, you agree to them. Please read them — they're written to be understandable."
      sections={[
        {
          heading: 'Using the service',
          body: (
            <>
              ielts.camp provides IELTS practice tests, AI feedback, and study tools for your
              personal exam preparation. You must be old enough to consent to data processing in
              your country, and you agree not to misuse the service, abuse the AI features, or
              attempt to disrupt the platform for others.
            </>
          ),
        },
        {
          heading: 'Your account',
          body: (
            <>
              You are responsible for keeping your login credentials secure and for activity under
              your account. One account is for one person — sharing accounts across multiple
              students requires a schools plan.
            </>
          ),
        },
        {
          heading: 'Subscriptions & billing',
          body: (
            <>
              Paid plans are billed in advance through Stripe on a monthly or annual basis. Your
              subscription renews automatically until cancelled. You can cancel anytime from
              Settings; access continues until the end of the current billing period.
            </>
          ),
        },
        {
          heading: 'Refunds',
          body: (
            <>
              We offer a 7-day refund on first-time paid plans if the service isn&apos;t right for
              you — just email us within 7 days of purchase. Renewals are non-refundable, so cancel
              before your renewal date if you don&apos;t wish to continue.
            </>
          ),
        },
        {
          heading: 'AI feedback disclaimer',
          body: (
            <>
              AI band estimates and feedback are practice guidance, not official IELTS scores. They
              are generated by automated models and may not perfectly match an official examiner.
              Use them to improve — not as a guarantee of your real exam result.
            </>
          ),
        },
        {
          heading: 'Content & intellectual property',
          body: (
            <>
              Practice materials and the platform are owned by ielts.camp. The essays and responses
              you submit remain yours. IELTS™ is a trademark of its respective owners; ielts.camp is
              an independent preparation tool and is not affiliated with or endorsed by them.
            </>
          ),
        },
        {
          heading: 'Changes to these terms',
          body: (
            <>
              We may update these terms as the product evolves. If we make material changes,
              we&apos;ll notify you in-app or by email. Continued use after changes means you accept
              the updated terms.
            </>
          ),
        },
      ]}
    />
  )
}
