-- ============================================================
-- IELTS Vocabulary bank: decks + words (+ per-user SRS progress)
-- Generated by scripts/gen-vocab.mjs — do not edit by hand.
-- ============================================================

create table if not exists vocabulary_decks (
  id           uuid primary key default uuid_generate_v4(),
  slug         text not null unique,
  title        text not null,
  description  text not null,
  category     text not null check (category in ('topic', 'function')),
  color        text not null default 'var(--accent)',
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now()
);

create table if not exists vocabulary_words (
  id              uuid primary key default uuid_generate_v4(),
  deck_id         uuid not null references vocabulary_decks(id) on delete cascade,
  word            text not null,
  part_of_speech  text not null,
  ipa             text,
  definition      text not null,
  example         text not null,
  synonyms        text[] not null default '{}',
  antonyms        text[] not null default '{}',
  band_level      text not null,
  created_at      timestamptz not null default now(),
  unique (deck_id, word)
);

create table if not exists user_vocabulary (
  id             uuid primary key default uuid_generate_v4(),
  user_id        uuid not null references profiles(id) on delete cascade,
  word_id        uuid not null references vocabulary_words(id) on delete cascade,
  status         text not null default 'new' check (status in ('new', 'learning', 'learned')),
  ease           numeric(3,2) not null default 2.5,
  interval_days  integer not null default 0,
  repetitions    integer not null default 0,
  due_at         timestamptz not null default now(),
  last_result    text check (last_result in ('again', 'hard', 'good', 'easy')),
  reviewed_at    timestamptz,
  created_at     timestamptz not null default now(),
  unique (user_id, word_id)
);

create index if not exists idx_vocabulary_words_deck on vocabulary_words(deck_id);
create index if not exists idx_user_vocabulary_due   on user_vocabulary(user_id, due_at);

-- ── Row level security ──────────────────────────────────────────────────────
alter table vocabulary_decks enable row level security;
alter table vocabulary_words enable row level security;
alter table user_vocabulary  enable row level security;

drop policy if exists "Anyone can read vocabulary decks" on vocabulary_decks;
create policy "Anyone can read vocabulary decks" on vocabulary_decks for select using (true);

drop policy if exists "Anyone can read vocabulary words" on vocabulary_words;
create policy "Anyone can read vocabulary words" on vocabulary_words for select using (true);

drop policy if exists "Users read own vocab progress"   on user_vocabulary;
drop policy if exists "Users insert own vocab progress" on user_vocabulary;
drop policy if exists "Users update own vocab progress" on user_vocabulary;
create policy "Users read own vocab progress"   on user_vocabulary for select using (auth.uid() = user_id);
create policy "Users insert own vocab progress" on user_vocabulary for insert with check (auth.uid() = user_id);
create policy "Users update own vocab progress" on user_vocabulary for update using (auth.uid() = user_id);


-- ── Decks ───────────────────────────────────────────────────────────────────
insert into vocabulary_decks (slug, title, description, category, color, sort_order) values
  ('education', 'Education', 'Schooling, learning and academic life — for Writing Task 2 and Speaking.', 'topic', 'var(--info)', 0),
  ('environment', 'Environment & Climate', 'Climate change, pollution and sustainability vocabulary for essays and discussion.', 'topic', 'var(--accent)', 1),
  ('technology', 'Technology & Internet', 'Digital life, automation and the internet — common across all IELTS modules.', 'topic', '#6b46c1', 2),
  ('health', 'Health & Lifestyle', 'Diet, fitness, healthcare and well-being — frequent Writing and Speaking themes.', 'topic', 'var(--danger)', 3),
  ('workEconomy', 'Work & Economy', 'Careers, business and the economy — essential for Task 2 and Part 3 discussion.', 'topic', 'var(--warn)', 4),
  ('crimeLaw', 'Crime & Law', 'Justice, punishment and policing — a classic Writing Task 2 and Part 3 topic.', 'topic', '#475569', 5),
  ('societyCulture', 'Society & Culture', 'Tradition, diversity and social change — high-value for Writing and Speaking.', 'topic', '#0d9488', 6),
  ('government', 'Government & Globalisation', 'Politics, policy and global affairs — advanced vocabulary for Task 2 essays.', 'topic', '#2563eb', 7),
  ('media', 'Media & Advertising', 'News, social media and advertising — increasingly common across IELTS topics.', 'topic', '#db2777', 8),
  ('travel', 'Travel & Tourism', 'Tourism, transport and travel — handy for Speaking and Task 2 essays.', 'topic', '#0891b2', 9),
  ('awl', 'Academic Word List', 'Core high-frequency words from academic English — the backbone of Task 2 writing.', 'function', 'var(--accent)', 10),
  ('linkers', 'Linkers & Cohesion', 'Connectives for sequencing, contrasting and exemplifying — the glue of essays.', 'function', 'var(--warn)', 11),
  ('collocations', 'High-band Collocations', 'Natural word partnerships that examiners reward — ready-made for essays.', 'function', 'var(--info)', 12),
  ('speakingIdioms', 'Speaking · Part 3 & Idioms', 'Natural phrases and idioms that lift fluency in the Speaking interview.', 'function', 'var(--danger)', 13)
on conflict (slug) do update set
  title = excluded.title, description = excluded.description,
  category = excluded.category, color = excluded.color, sort_order = excluded.sort_order;

-- ── Education (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('curriculum', 'n', '/kəˈrɪkjələm/', 'The subjects that make up a course of study at a school or college.', 'The national curriculum places a heavy emphasis on science and mathematics.', array['syllabus', 'programme']::text[], '{}'::text[], '7.0'),
  ('rote learning', 'phrase', '/rəʊt ˈlɜːnɪŋ/', 'Memorising information through repetition rather than understanding.', 'Critics argue that rote learning stifles a child’s natural curiosity.', array['memorisation', 'cramming']::text[], array['active learning']::text[], '7.5'),
  ('literacy', 'n', '/ˈlɪtərəsi/', 'The ability to read and write.', 'Adult literacy programmes have transformed employment prospects in rural areas.', array['reading ability']::text[], array['illiteracy']::text[], '6.5'),
  ('vocational', 'adj', '/vəʊˈkeɪʃənl/', 'Relating to training for a specific job or trade.', 'Vocational courses equip students with practical, job-ready skills.', array['practical', 'occupational']::text[], array['academic']::text[], '7.0'),
  ('pedagogy', 'n', '/ˈpedəɡɒdʒi/', 'The method and practice of teaching.', 'Modern pedagogy favours collaboration over passive listening.', array['teaching method']::text[], '{}'::text[], '8.0'),
  ('truancy', 'n', '/ˈtruːənsi/', 'The act of staying away from school without permission.', 'Schools have introduced fines to combat persistent truancy.', array['absenteeism']::text[], array['attendance']::text[], '7.5'),
  ('holistic', 'adj', '/həˈlɪstɪk/', 'Considering the whole person or system rather than just one part.', 'A holistic education nurtures emotional as well as academic growth.', array['comprehensive', 'all-round']::text[], array['narrow']::text[], '7.5'),
  ('discipline', 'n', '/ˈdɪsəplɪn/', 'Controlled, orderly behaviour, or training that produces it.', 'Strict discipline in the classroom can either focus or intimidate pupils.', array['order', 'self-control']::text[], array['disorder']::text[], '6.5'),
  ('enrol', 'v', '/ɪnˈrəʊl/', 'To officially register as a member or student.', 'Thousands of mature students enrol on online degrees each year.', array['register', 'sign up']::text[], array['withdraw']::text[], '6.5'),
  ('scholarship', 'n', '/ˈskɒləʃɪp/', 'A grant of money to support a student’s education.', 'She won a full scholarship to study engineering abroad.', array['grant', 'bursary']::text[], '{}'::text[], '6.5'),
  ('curiosity', 'n', '/ˌkjʊəriˈɒsəti/', 'A strong desire to learn or know something.', 'Good teachers spark curiosity rather than simply transmit facts.', array['inquisitiveness', 'interest']::text[], array['indifference']::text[], '7.0'),
  ('rigorous', 'adj', '/ˈrɪɡərəs/', 'Extremely thorough, careful and demanding.', 'Medical training is famously rigorous and competitive.', array['demanding', 'exacting']::text[], array['lax', 'lenient']::text[], '7.5'),
  ('aptitude', 'n', '/ˈæptɪtjuːd/', 'A natural ability or talent for something.', 'The test is designed to measure a candidate’s aptitude for languages.', array['talent', 'flair']::text[], array['inability']::text[], '7.5'),
  ('interactive', 'adj', '/ˌɪntərˈæktɪv/', 'Involving active participation between people or with technology.', 'Interactive whiteboards have made lessons far more engaging.', array['participatory', 'hands-on']::text[], array['passive']::text[], '6.5'),
  ('comprehension', 'n', '/ˌkɒmprɪˈhenʃn/', 'The ability to understand something.', 'Reading comprehension improves dramatically with daily practice.', array['understanding', 'grasp']::text[], array['confusion']::text[], '6.5'),
  ('tuition', 'n', '/tjuˈɪʃn/', 'Teaching, especially of an individual or small group; also course fees.', 'Private tuition has become a booming industry in many countries.', array['instruction', 'coaching']::text[], '{}'::text[], '7.0'),
  ('underachieve', 'v', '/ˌʌndərəˈtʃiːv/', 'To do less well than one is capable of.', 'Boys are statistically more likely to underachieve at school.', array['underperform']::text[], array['excel']::text[], '7.5'),
  ('well-rounded', 'adj', '/ˌwel ˈraʊndɪd/', 'Having a wide range of abilities, interests or experiences.', 'Universities increasingly seek well-rounded rather than narrowly gifted applicants.', array['versatile', 'balanced']::text[], array['one-dimensional']::text[], '7.0'),
  ('mandatory', 'adj', '/ˈmændətəri/', 'Required by law or rules; compulsory.', 'In most countries, schooling is mandatory until the age of sixteen.', array['compulsory', 'obligatory']::text[], array['optional', 'voluntary']::text[], '7.0'),
  ('intellectual', 'adj', '/ˌɪntəˈlektʃuəl/', 'Relating to the ability to think and understand ideas.', 'Debating clubs offer valuable intellectual stimulation.', array['cerebral', 'cognitive']::text[], '{}'::text[], '7.0'),
  ('nurture', 'v', '/ˈnɜːtʃə/', 'To care for and encourage the growth or development of someone.', 'Parents and teachers must work together to nurture a child’s talents.', array['foster', 'cultivate']::text[], array['neglect', 'stifle']::text[], '7.5'),
  ('streaming', 'n', '/ˈstriːmɪŋ/', 'Grouping pupils by ability into separate classes.', 'Streaming can motivate top students but discourage weaker ones.', array['setting', 'tracking']::text[], array['mixed-ability']::text[], '7.5'),
  ('proficiency', 'n', '/prəˈfɪʃnsi/', 'A high degree of skill or competence.', 'Employers now expect proficiency in at least one foreign language.', array['competence', 'mastery']::text[], array['incompetence']::text[], '7.5'),
  ('curtail', 'v', '/kɜːˈteɪl/', 'To reduce or restrict something.', 'Budget cuts have curtailed extracurricular activities in state schools.', array['restrict', 'cut back']::text[], array['expand']::text[], '8.0'),
  ('fee-paying', 'adj', '/ˈfiː ˌpeɪɪŋ/', 'Describing private schools that charge tuition.', 'Critics claim fee-paying schools entrench social inequality.', array['private', 'independent']::text[], array['state']::text[], '7.0'),
  ('lifelong', 'adj', '/ˈlaɪflɒŋ/', 'Continuing throughout a person’s life.', 'The internet has made lifelong learning accessible to almost everyone.', array['continuous', 'ongoing']::text[], array['short-term']::text[], '6.5'),
  ('cognitive', 'adj', '/ˈkɒɡnətɪv/', 'Relating to mental processes of thinking and learning.', 'Bilingual children often show enhanced cognitive flexibility.', array['mental', 'intellectual']::text[], '{}'::text[], '8.0'),
  ('dropout', 'n', '/ˈdrɒpaʊt/', 'A person who leaves school or a course before finishing.', 'High dropout rates often reflect deeper social problems.', array['quitter', 'leaver']::text[], array['graduate']::text[], '7.0'),
  ('stimulating', 'adj', '/ˈstɪmjəleɪtɪŋ/', 'Encouraging interest, thought or enthusiasm.', 'A stimulating classroom environment keeps young learners engaged.', array['engaging', 'inspiring']::text[], array['dull', 'tedious']::text[], '7.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'education'
on conflict (deck_id, word) do nothing;

-- ── Environment & Climate (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('sustainable', 'adj', '/səˈsteɪnəbl/', 'Able to continue over time without harming the environment.', 'Governments are under pressure to invest in sustainable energy.', array['eco-friendly', 'renewable']::text[], array['unsustainable']::text[], '7.0'),
  ('emissions', 'n', '/ɪˈmɪʃnz/', 'Gases or substances released into the atmosphere.', 'Carbon emissions must fall sharply to limit global warming.', array['discharge', 'output']::text[], '{}'::text[], '6.5'),
  ('deforestation', 'n', '/ˌdiːˌfɒrɪˈsteɪʃn/', 'The clearing of forests on a large scale.', 'Deforestation in the Amazon threatens countless species.', array['clearance', 'logging']::text[], array['reforestation']::text[], '7.0'),
  ('biodiversity', 'n', '/ˌbaɪəʊdaɪˈvɜːsəti/', 'The variety of plant and animal life in a habitat.', 'Protecting biodiversity is essential for a stable ecosystem.', array['variety of life']::text[], '{}'::text[], '7.5'),
  ('renewable', 'adj', '/rɪˈnjuːəbl/', 'Able to be replenished naturally, like solar or wind power.', 'Renewable sources now supply a third of the country’s electricity.', array['sustainable', 'green']::text[], array['finite', 'fossil']::text[], '6.5'),
  ('degradation', 'n', '/ˌdeɡrəˈdeɪʃn/', 'The process of damaging or lowering the quality of something.', 'Soil degradation is reducing crop yields across the region.', array['deterioration', 'decline']::text[], array['restoration']::text[], '7.5'),
  ('carbon footprint', 'phrase', '/ˈkɑːbən ˈfʊtprɪnt/', 'The total amount of greenhouse gases produced by an activity.', 'Cycling to work is a simple way to shrink your carbon footprint.', array['emissions impact']::text[], '{}'::text[], '7.0'),
  ('conservation', 'n', '/ˌkɒnsəˈveɪʃn/', 'The protection of nature and natural resources.', 'Wildlife conservation depends heavily on local community support.', array['preservation', 'protection']::text[], array['exploitation']::text[], '6.5'),
  ('depletion', 'n', '/dɪˈpliːʃn/', 'The reduction of a resource until it runs low.', 'The depletion of fish stocks endangers coastal economies.', array['exhaustion', 'reduction']::text[], array['replenishment']::text[], '7.5'),
  ('ecosystem', 'n', '/ˈiːkəʊsɪstəm/', 'A community of living things and their environment.', 'Coral reefs support some of the richest ecosystems on Earth.', array['habitat', 'biome']::text[], '{}'::text[], '7.0'),
  ('mitigate', 'v', '/ˈmɪtɪɡeɪt/', 'To make something less harmful or severe.', 'Planting trees can help mitigate the effects of climate change.', array['alleviate', 'reduce']::text[], array['aggravate', 'worsen']::text[], '8.0'),
  ('pollutant', 'n', '/pəˈluːtənt/', 'A substance that contaminates air, water or soil.', 'Industrial pollutants have poisoned the river for decades.', array['contaminant', 'toxin']::text[], '{}'::text[], '7.0'),
  ('offset', 'v', '/ˌɒfˈset/', 'To counterbalance or compensate for something.', 'Airlines let passengers offset their flights by funding tree planting.', array['counterbalance', 'compensate']::text[], '{}'::text[], '7.5'),
  ('greenhouse gas', 'phrase', '/ˈɡriːnhaʊs ɡæs/', 'A gas that traps heat in the atmosphere.', 'Methane is a far more potent greenhouse gas than carbon dioxide.', '{}'::text[], '{}'::text[], '6.5'),
  ('habitat', 'n', '/ˈhæbɪtæt/', 'The natural home of a plant or animal.', 'Urban sprawl is destroying the habitat of many native birds.', array['environment', 'home']::text[], '{}'::text[], '6.5'),
  ('finite', 'adj', '/ˈfaɪnaɪt/', 'Limited in amount; not endless.', 'Fossil fuels are a finite resource that will eventually run out.', array['limited', 'exhaustible']::text[], array['infinite', 'renewable']::text[], '7.5'),
  ('contaminate', 'v', '/kənˈtæmɪneɪt/', 'To make something impure or poisonous.', 'Leaking pipelines can contaminate the local water supply.', array['pollute', 'taint']::text[], array['purify']::text[], '7.0'),
  ('eco-friendly', 'adj', '/ˈiːkəʊ ˈfrendli/', 'Not harmful to the environment.', 'The company has switched to eco-friendly packaging.', array['green', 'sustainable']::text[], array['polluting']::text[], '6.5'),
  ('extinction', 'n', '/ɪkˈstɪŋkʃn/', 'The state of a species no longer existing.', 'Several species face extinction within our lifetime.', array['dying out', 'eradication']::text[], array['survival']::text[], '7.0'),
  ('drought', 'n', '/draʊt/', 'A long period of abnormally low rainfall.', 'Prolonged drought has devastated the harvest this year.', array['dry spell', 'water shortage']::text[], array['flood']::text[], '6.5'),
  ('exacerbate', 'v', '/ɪɡˈzæsəbeɪt/', 'To make a problem or bad situation worse.', 'Burning coal will only exacerbate air pollution in cities.', array['aggravate', 'worsen']::text[], array['alleviate', 'ease']::text[], '8.0'),
  ('scarcity', 'n', '/ˈskeəsəti/', 'A shortage or insufficient supply of something.', 'Water scarcity could trigger conflicts in the coming decades.', array['shortage', 'dearth']::text[], array['abundance']::text[], '7.5'),
  ('recycle', 'v', '/ˌriːˈsaɪkl/', 'To process waste so it can be used again.', 'Households are encouraged to recycle glass, paper and plastic.', array['reuse', 'reprocess']::text[], array['discard']::text[], '6.5'),
  ('fragile', 'adj', '/ˈfrædʒaɪl/', 'Easily damaged or destroyed; delicate.', 'The Arctic is a fragile environment highly sensitive to warming.', array['delicate', 'vulnerable']::text[], array['robust', 'resilient']::text[], '7.0'),
  ('sustainability', 'n', '/səˌsteɪnəˈbɪləti/', 'The ability to maintain something without depleting resources.', 'Sustainability has become central to corporate strategy.', array['viability']::text[], '{}'::text[], '7.5'),
  ('hazardous', 'adj', '/ˈhæzədəs/', 'Dangerous or risky, especially to health.', 'Hazardous waste must be disposed of under strict regulation.', array['dangerous', 'perilous']::text[], array['safe', 'harmless']::text[], '7.0'),
  ('replenish', 'v', '/rɪˈplenɪʃ/', 'To fill something up again or restore a supply.', 'Aquifers take centuries to replenish once they are drained.', array['refill', 'restore']::text[], array['deplete']::text[], '8.0'),
  ('arable', 'adj', '/ˈærəbl/', 'Suitable for growing crops.', 'Climate change is shrinking the world’s arable land.', array['fertile', 'cultivable']::text[], array['barren']::text[], '8.0'),
  ('catastrophic', 'adj', '/ˌkætəˈstrɒfɪk/', 'Involving sudden, large-scale disaster.', 'Unchecked warming could have catastrophic consequences.', array['disastrous', 'devastating']::text[], array['harmless']::text[], '7.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'environment'
on conflict (deck_id, word) do nothing;

-- ── Technology & Internet (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('automation', 'n', '/ˌɔːtəˈmeɪʃn/', 'The use of machines to do work previously done by people.', 'Automation is reshaping factories and threatening some jobs.', array['mechanisation']::text[], array['manual labour']::text[], '7.0'),
  ('innovation', 'n', '/ˌɪnəˈveɪʃn/', 'A new method, idea or product.', 'Constant innovation keeps technology companies ahead of rivals.', array['invention', 'breakthrough']::text[], array['stagnation']::text[], '6.5'),
  ('obsolete', 'adj', '/ˈɒbsəliːt/', 'No longer in use because something newer exists.', 'Smartphones have rendered many gadgets obsolete.', array['outdated', 'antiquated']::text[], array['current', 'modern']::text[], '7.5'),
  ('cutting-edge', 'adj', '/ˈkʌtɪŋ edʒ/', 'At the most advanced stage of development.', 'The lab uses cutting-edge artificial intelligence.', array['state-of-the-art', 'advanced']::text[], array['outdated']::text[], '7.0'),
  ('surveillance', 'n', '/səˈveɪləns/', 'Close observation, especially of a suspect or the public.', 'Cities are increasingly covered by surveillance cameras.', array['monitoring', 'observation']::text[], '{}'::text[], '7.5'),
  ('connectivity', 'n', '/ˌkɒnekˈtɪvəti/', 'The state of being connected, especially to the internet.', 'Rural areas still suffer from poor internet connectivity.', array['access', 'linkage']::text[], '{}'::text[], '7.0'),
  ('addictive', 'adj', '/əˈdɪktɪv/', 'Causing a strong, harmful urge to keep doing something.', 'Social media apps are deliberately designed to be addictive.', array['compulsive', 'habit-forming']::text[], '{}'::text[], '6.5'),
  ('disruptive', 'adj', '/dɪsˈrʌptɪv/', 'Radically changing an existing industry or market.', 'Streaming was a disruptive technology that destroyed video rental.', array['revolutionary', 'transformative']::text[], '{}'::text[], '7.5'),
  ('glitch', 'n', '/ɡlɪtʃ/', 'A small, temporary fault in a system.', 'A software glitch briefly took the banking app offline.', array['malfunction', 'bug']::text[], '{}'::text[], '7.0'),
  ('encryption', 'n', '/ɪnˈkrɪpʃn/', 'The process of converting data into a secure code.', 'End-to-end encryption protects messages from eavesdroppers.', array['encoding']::text[], array['decryption']::text[], '8.0'),
  ('streamline', 'v', '/ˈstriːmlaɪn/', 'To make a process simpler and more efficient.', 'The new platform streamlines the entire booking process.', array['simplify', 'optimise']::text[], array['complicate']::text[], '7.5'),
  ('accessible', 'adj', '/əkˈsesəbl/', 'Able to be reached, used or understood easily.', 'Online courses have made higher education far more accessible.', array['available', 'reachable']::text[], array['inaccessible']::text[], '6.5'),
  ('malware', 'n', '/ˈmælweə/', 'Software designed to damage or gain access to a computer.', 'A single click on the link installed malware on the network.', array['virus', 'spyware']::text[], '{}'::text[], '7.0'),
  ('digital divide', 'phrase', '/ˈdɪdʒɪtl dɪˈvaɪd/', 'The gap between those with and without internet access.', 'The pandemic exposed a stark digital divide between rich and poor.', '{}'::text[], '{}'::text[], '7.5'),
  ('user-friendly', 'adj', '/ˈjuːzə ˈfrendli/', 'Easy to use or understand.', 'The interface is clean, intuitive and user-friendly.', array['intuitive', 'accessible']::text[], array['complicated']::text[], '6.5'),
  ('integrate', 'v', '/ˈɪntɪɡreɪt/', 'To combine parts so they work together as a whole.', 'The app integrates seamlessly with your calendar and email.', array['combine', 'merge']::text[], array['separate']::text[], '7.0'),
  ('anonymity', 'n', '/ˌænəˈnɪməti/', 'The state of being unknown or unnamed.', 'Online anonymity can encourage abusive behaviour.', array['namelessness']::text[], array['identity']::text[], '8.0'),
  ('artificial intelligence', 'phrase', '/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/', 'Computer systems able to perform tasks needing human intelligence.', 'Artificial intelligence is now used to diagnose certain diseases.', array['AI', 'machine learning']::text[], '{}'::text[], '7.0'),
  ('versatile', 'adj', '/ˈvɜːsətaɪl/', 'Able to adapt or be used for many purposes.', 'The device is remarkably versatile, doubling as a camera and phone.', array['adaptable', 'multipurpose']::text[], array['limited']::text[], '7.5'),
  ('data breach', 'phrase', '/ˈdeɪtə briːtʃ/', 'An incident where confidential data is accessed illegally.', 'The data breach exposed millions of customers’ passwords.', array['leak', 'hack']::text[], '{}'::text[], '7.0'),
  ('intuitive', 'adj', '/ɪnˈtjuːɪtɪv/', 'Easy to understand or use without instruction.', 'Good design feels intuitive even to first-time users.', array['instinctive', 'user-friendly']::text[], array['confusing']::text[], '7.5'),
  ('redundant', 'adj', '/rɪˈdʌndənt/', 'No longer needed or useful; superfluous.', 'Automation has made some clerical roles redundant.', array['superfluous', 'unnecessary']::text[], array['essential']::text[], '7.5'),
  ('proliferate', 'v', '/prəˈlɪfəreɪt/', 'To increase rapidly in number.', 'Fake news sites proliferated during the election.', array['multiply', 'mushroom']::text[], array['dwindle']::text[], '8.0'),
  ('seamless', 'adj', '/ˈsiːmləs/', 'Smooth and continuous, with no awkward gaps.', 'The update offers a seamless transition between devices.', array['smooth', 'fluid']::text[], array['disjointed']::text[], '7.5'),
  ('gadget', 'n', '/ˈɡædʒɪt/', 'A small, clever mechanical or electronic device.', 'The shop is full of gadgets that few people actually need.', array['device', 'gizmo']::text[], '{}'::text[], '6.5'),
  ('outdated', 'adj', '/ˌaʊtˈdeɪtɪd/', 'Old-fashioned and no longer useful.', 'Many schools still rely on outdated computer equipment.', array['obsolete', 'antiquated']::text[], array['modern', 'current']::text[], '6.5'),
  ('revolutionise', 'v', '/ˌrevəˈluːʃənaɪz/', 'To change something completely and fundamentally.', 'The smartphone revolutionised the way we communicate.', array['transform', 'overhaul']::text[], '{}'::text[], '7.5'),
  ('screen time', 'phrase', '/ˈskriːn taɪm/', 'Time spent using a device with a screen.', 'Doctors warn that excessive screen time harms children’s sleep.', '{}'::text[], '{}'::text[], '6.5'),
  ('cyberbullying', 'n', '/ˈsaɪbəˌbʊliɪŋ/', 'The use of digital platforms to harass or intimidate.', 'Schools now run workshops to tackle cyberbullying.', array['online harassment']::text[], '{}'::text[], '7.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'technology'
on conflict (deck_id, word) do nothing;

-- ── Health & Lifestyle (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('sedentary', 'adj', '/ˈsedntri/', 'Involving little physical activity; spent sitting down.', 'A sedentary lifestyle is linked to obesity and heart disease.', array['inactive', 'desk-bound']::text[], array['active']::text[], '7.5'),
  ('nutritious', 'adj', '/njuˈtrɪʃəs/', 'Containing substances that nourish the body.', 'Children need a balanced, nutritious diet to grow properly.', array['nourishing', 'wholesome']::text[], array['unhealthy']::text[], '6.5'),
  ('epidemic', 'n', '/ˌepɪˈdemɪk/', 'A widespread occurrence of a disease in a community.', 'Health officials struggled to contain the flu epidemic.', array['outbreak', 'plague']::text[], '{}'::text[], '7.0'),
  ('well-being', 'n', '/ˈwel ˈbiːɪŋ/', 'The state of being comfortable, healthy and happy.', 'Employers are paying more attention to staff well-being.', array['welfare', 'wellness']::text[], '{}'::text[], '6.5'),
  ('preventive', 'adj', '/prɪˈventɪv/', 'Designed to stop something, especially illness, before it happens.', 'Preventive medicine reduces the long-term burden on hospitals.', array['precautionary', 'protective']::text[], array['curative']::text[], '7.5'),
  ('chronic', 'adj', '/ˈkrɒnɪk/', 'Persisting for a long time or constantly recurring.', 'Diabetes is a chronic condition requiring lifelong management.', array['persistent', 'long-term']::text[], array['acute', 'temporary']::text[], '7.0'),
  ('obesity', 'n', '/əʊˈbiːsəti/', 'The condition of being extremely overweight.', 'Childhood obesity has tripled over the past generation.', array['excess weight']::text[], '{}'::text[], '6.5'),
  ('immunity', 'n', '/ɪˈmjuːnəti/', 'The body’s ability to resist a particular infection.', 'Vaccination builds immunity against serious diseases.', array['resistance']::text[], array['susceptibility']::text[], '7.0'),
  ('detrimental', 'adj', '/ˌdetrɪˈmentl/', 'Tending to cause harm or damage.', 'Excessive sugar is detrimental to both teeth and waistlines.', array['harmful', 'damaging']::text[], array['beneficial']::text[], '7.5'),
  ('rehabilitation', 'n', '/ˌriːəˌbɪlɪˈteɪʃn/', 'The process of restoring health or normal life after illness.', 'Physiotherapy is central to rehabilitation after surgery.', array['recovery', 'recuperation']::text[], '{}'::text[], '7.5'),
  ('contagious', 'adj', '/kənˈteɪdʒəs/', 'Able to be spread by direct or indirect contact.', 'Measles is highly contagious among unvaccinated children.', array['infectious', 'communicable']::text[], array['non-infectious']::text[], '7.0'),
  ('holistic', 'adj', '/həˈlɪstɪk/', 'Treating the whole person, including mind and lifestyle.', 'The clinic takes a holistic approach to chronic pain.', array['integrated', 'all-round']::text[], array['narrow']::text[], '7.5'),
  ('malnutrition', 'n', '/ˌmælnjuˈtrɪʃn/', 'Poor health caused by an inadequate or unbalanced diet.', 'Millions of children still suffer from malnutrition.', array['undernourishment']::text[], array['nourishment']::text[], '7.5'),
  ('ailment', 'n', '/ˈeɪlmənt/', 'A minor illness or health problem.', 'Common ailments such as colds rarely need antibiotics.', array['illness', 'complaint']::text[], '{}'::text[], '7.0'),
  ('therapeutic', 'adj', '/ˌθerəˈpjuːtɪk/', 'Having a healing or relaxing effect.', 'Gardening can have a genuinely therapeutic effect on the mind.', array['healing', 'restorative']::text[], array['harmful']::text[], '8.0'),
  ('susceptible', 'adj', '/səˈseptəbl/', 'Likely to be affected by something, especially illness.', 'The elderly are particularly susceptible to winter infections.', array['vulnerable', 'prone']::text[], array['resistant', 'immune']::text[], '7.5'),
  ('life expectancy', 'phrase', '/laɪf ɪkˈspektənsi/', 'The average period a person is expected to live.', 'Better healthcare has raised life expectancy worldwide.', '{}'::text[], '{}'::text[], '6.5'),
  ('fatigue', 'n', '/fəˈtiːɡ/', 'Extreme tiredness from exertion or illness.', 'Long shifts leave many nurses suffering from chronic fatigue.', array['exhaustion', 'tiredness']::text[], array['energy']::text[], '7.0'),
  ('abstain', 'v', '/əbˈsteɪn/', 'To choose not to do or consume something.', 'Athletes are advised to abstain from alcohol during training.', array['refrain', 'avoid']::text[], array['indulge']::text[], '8.0'),
  ('outbreak', 'n', '/ˈaʊtbreɪk/', 'The sudden start of something unwelcome, such as disease.', 'An outbreak of cholera followed the floods.', array['epidemic', 'eruption']::text[], '{}'::text[], '7.0'),
  ('balanced diet', 'phrase', '/ˈbælənst ˈdaɪət/', 'A diet containing the right variety and amounts of food.', 'A balanced diet is the foundation of good health.', '{}'::text[], '{}'::text[], '6.5'),
  ('invigorating', 'adj', '/ɪnˈvɪɡəreɪtɪŋ/', 'Making one feel healthy, fresh and energetic.', 'An early morning swim is wonderfully invigorating.', array['refreshing', 'energising']::text[], array['tiring']::text[], '8.0'),
  ('deteriorate', 'v', '/dɪˈtɪəriəreɪt/', 'To become progressively worse.', 'Without treatment, her condition rapidly deteriorated.', array['worsen', 'decline']::text[], array['improve', 'recover']::text[], '7.5'),
  ('hygiene', 'n', '/ˈhaɪdʒiːn/', 'Practices that maintain health and prevent disease.', 'Good hand hygiene dramatically reduces infection rates.', array['cleanliness', 'sanitation']::text[], '{}'::text[], '6.5'),
  ('addiction', 'n', '/əˈdɪkʃn/', 'The condition of being unable to stop using something harmful.', 'Smartphone addiction is a growing concern among teenagers.', array['dependency']::text[], '{}'::text[], '6.5'),
  ('robust', 'adj', '/rəʊˈbʌst/', 'Strong and healthy; not easily damaged.', 'Regular exercise keeps the immune system robust.', array['sturdy', 'vigorous']::text[], array['frail', 'fragile']::text[], '7.5'),
  ('moderation', 'n', '/ˌmɒdəˈreɪʃn/', 'The avoidance of excess; keeping within sensible limits.', 'Most foods are fine when eaten in moderation.', array['restraint', 'temperance']::text[], array['excess']::text[], '7.0'),
  ('ward off', 'phrase', '/wɔːd ɒf/', 'To prevent something harmful from affecting you.', 'A diet rich in fruit may help ward off illness.', array['fend off', 'avert']::text[], '{}'::text[], '7.5'),
  ('longevity', 'n', '/lɒnˈdʒevəti/', 'Long life or duration.', 'Researchers link the population’s longevity to its diet.', array['long life']::text[], '{}'::text[], '8.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'health'
on conflict (deck_id, word) do nothing;

-- ── Work & Economy (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('unemployment', 'n', '/ˌʌnɪmˈplɔɪmənt/', 'The state of not having a paid job.', 'Rising unemployment puts pressure on welfare systems.', array['joblessness']::text[], array['employment']::text[], '6.5'),
  ('entrepreneur', 'n', '/ˌɒntrəprəˈnɜː/', 'A person who sets up a business, taking financial risks.', 'Young entrepreneurs are reshaping the technology sector.', array['founder', 'businessperson']::text[], '{}'::text[], '7.0'),
  ('recession', 'n', '/rɪˈseʃn/', 'A period of temporary economic decline.', 'Many small firms collapsed during the recession.', array['downturn', 'slump']::text[], array['boom', 'recovery']::text[], '7.0'),
  ('lucrative', 'adj', '/ˈluːkrətɪv/', 'Producing a great deal of profit.', 'Software development remains a highly lucrative career.', array['profitable', 'well-paid']::text[], array['unprofitable']::text[], '7.5'),
  ('workforce', 'n', '/ˈwɜːkfɔːs/', 'The people available for or engaged in work.', 'Automation is transforming the skills the workforce needs.', array['labour force', 'staff']::text[], '{}'::text[], '6.5'),
  ('incentive', 'n', '/ɪnˈsentɪv/', 'Something that motivates or encourages action.', 'Tax breaks act as an incentive for firms to invest.', array['motivation', 'inducement']::text[], array['deterrent']::text[], '7.5'),
  ('redundancy', 'n', '/rɪˈdʌndənsi/', 'The loss of a job because it is no longer needed.', 'The factory closure led to hundreds of redundancies.', array['layoff', 'dismissal']::text[], '{}'::text[], '7.5'),
  ('productivity', 'n', '/ˌprɒdʌkˈtɪvəti/', 'The rate at which goods or work are produced.', 'Flexible hours can actually boost productivity.', array['efficiency', 'output']::text[], '{}'::text[], '7.0'),
  ('remuneration', 'n', '/rɪˌmjuːnəˈreɪʃn/', 'Payment or compensation for work or services.', 'The role offers generous remuneration and benefits.', array['pay', 'salary']::text[], '{}'::text[], '8.0'),
  ('outsource', 'v', '/ˈaʊtsɔːs/', 'To pay an outside company to do work internally done.', 'Many firms outsource customer service to cut costs.', array['contract out', 'subcontract']::text[], array['insource']::text[], '7.5'),
  ('stagnant', 'adj', '/ˈstæɡnənt/', 'Not growing, developing or progressing.', 'Wages have remained stagnant despite rising prices.', array['static', 'flat']::text[], array['booming', 'growing']::text[], '7.5'),
  ('recruitment', 'n', '/rɪˈkruːtmənt/', 'The process of finding and hiring new staff.', 'The company has frozen recruitment until next year.', array['hiring']::text[], '{}'::text[], '6.5'),
  ('monopoly', 'n', '/məˈnɒpəli/', 'Exclusive control of a market by one supplier.', 'Regulators worry that the merger could create a monopoly.', array['domination']::text[], array['competition']::text[], '7.5'),
  ('expertise', 'n', '/ˌekspɜːˈtiːz/', 'Expert skill or knowledge in a particular field.', 'Foreign firms are hired for their technical expertise.', array['proficiency', 'know-how']::text[], array['inexperience']::text[], '7.0'),
  ('fluctuate', 'v', '/ˈflʌktʃueɪt/', 'To rise and fall irregularly.', 'Oil prices fluctuate in response to global events.', array['vary', 'oscillate']::text[], array['stabilise']::text[], '7.5'),
  ('self-employed', 'adj', '/ˌself ɪmˈplɔɪd/', 'Working for oneself rather than an employer.', 'The number of self-employed workers has surged online.', array['freelance', 'independent']::text[], array['salaried']::text[], '6.5'),
  ('subsidy', 'n', '/ˈsʌbsədi/', 'Money paid by a government to support an industry.', 'Farmers depend on subsidies to stay in business.', array['grant', 'support']::text[], '{}'::text[], '7.5'),
  ('thrive', 'v', '/θraɪv/', 'To grow, develop or be successful.', 'Small businesses thrive when red tape is reduced.', array['flourish', 'prosper']::text[], array['struggle', 'fail']::text[], '7.0'),
  ('affluent', 'adj', '/ˈæfluənt/', 'Having a great deal of money; wealthy.', 'The policy mainly benefits the most affluent households.', array['wealthy', 'prosperous']::text[], array['poor', 'deprived']::text[], '7.5'),
  ('workload', 'n', '/ˈwɜːkləʊd/', 'The amount of work to be done by someone.', 'An unmanageable workload often leads to burnout.', array['burden']::text[], '{}'::text[], '6.5'),
  ('vacancy', 'n', '/ˈveɪkənsi/', 'A job position that is available.', 'The firm advertised several vacancies in marketing.', array['opening', 'position']::text[], '{}'::text[], '6.5'),
  ('inflation', 'n', '/ɪnˈfleɪʃn/', 'A general rise in prices and fall in money’s value.', 'Soaring inflation has eroded household savings.', array['price rise']::text[], array['deflation']::text[], '7.0'),
  ('diligent', 'adj', '/ˈdɪlɪdʒənt/', 'Showing careful and persistent effort in work.', 'She earned promotion through diligent, consistent work.', array['hardworking', 'conscientious']::text[], array['lazy', 'negligent']::text[], '7.5'),
  ('startup', 'n', '/ˈstɑːtʌp/', 'A newly established business, often in technology.', 'The city has become a magnet for tech startups.', array['new venture']::text[], '{}'::text[], '6.5'),
  ('burnout', 'n', '/ˈbɜːnaʊt/', 'Physical or mental collapse from overwork.', 'Long hours and constant pressure caused widespread burnout.', array['exhaustion']::text[], '{}'::text[], '7.0'),
  ('feasible', 'adj', '/ˈfiːzəbl/', 'Possible to do easily or conveniently.', 'A four-day week is feasible for many office jobs.', array['viable', 'practical']::text[], array['impractical']::text[], '7.5'),
  ('prosperity', 'n', '/prɒsˈperəti/', 'The state of being successful, especially financially.', 'Trade brought decades of prosperity to the region.', array['wealth', 'affluence']::text[], array['poverty', 'hardship']::text[], '7.0'),
  ('meticulous', 'adj', '/məˈtɪkjələs/', 'Showing great attention to detail; very careful.', 'Accountants must be meticulous about every figure.', array['thorough', 'precise']::text[], array['careless', 'sloppy']::text[], '8.0'),
  ('exploit', 'v', '/ɪkˈsplɔɪt/', 'To use unfairly for one’s own advantage.', 'Some employers exploit migrant workers with low pay.', array['take advantage of', 'misuse']::text[], array['respect']::text[], '7.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'workEconomy'
on conflict (deck_id, word) do nothing;

-- ── Crime & Law (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('deterrent', 'n', '/dɪˈterənt/', 'Something that discourages an action, especially crime.', 'Many doubt that prison is an effective deterrent.', array['discouragement']::text[], array['incentive']::text[], '7.0'),
  ('rehabilitate', 'v', '/ˌriːəˈbɪlɪteɪt/', 'To help an offender return to a normal, law-abiding life.', 'Prisons should aim to rehabilitate, not merely punish.', array['reform', 'reintegrate']::text[], array['punish']::text[], '7.5'),
  ('offender', 'n', '/əˈfendə/', 'A person who commits a crime.', 'First-time offenders are often given community service.', array['criminal', 'culprit']::text[], array['victim']::text[], '6.5'),
  ('lenient', 'adj', '/ˈliːniənt/', 'More merciful or tolerant than expected.', 'Critics say the sentence was far too lenient.', array['merciful', 'soft']::text[], array['harsh', 'severe']::text[], '7.5'),
  ('surveillance', 'n', '/səˈveɪləns/', 'Close watch kept over someone or somewhere.', 'CCTV surveillance has expanded into residential streets.', array['monitoring']::text[], '{}'::text[], '7.5'),
  ('prosecute', 'v', '/ˈprɒsɪkjuːt/', 'To formally charge and try someone for a crime.', 'The company was prosecuted for dumping toxic waste.', array['charge', 'indict']::text[], array['defend']::text[], '7.0'),
  ('corruption', 'n', '/kəˈrʌpʃn/', 'Dishonest or illegal behaviour by those in power.', 'Widespread corruption undermines public trust in government.', array['bribery', 'dishonesty']::text[], array['integrity']::text[], '7.0'),
  ('vandalism', 'n', '/ˈvændəlɪzəm/', 'Deliberate destruction of or damage to property.', 'Vandalism costs the city millions in repairs each year.', array['destruction']::text[], '{}'::text[], '6.5'),
  ('incarceration', 'n', '/ɪnˌkɑːsəˈreɪʃn/', 'The state of being confined in prison.', 'Long incarceration rarely reduces reoffending.', array['imprisonment', 'detention']::text[], array['release', 'freedom']::text[], '8.0'),
  ('felony', 'n', '/ˈfeləni/', 'A serious crime, more grave than a misdemeanour.', 'Armed robbery is classified as a felony.', array['serious crime']::text[], array['misdemeanour']::text[], '7.5'),
  ('enforce', 'v', '/ɪnˈfɔːs/', 'To make sure a law or rule is obeyed.', 'Police struggle to enforce the speed limit in rural areas.', array['impose', 'implement']::text[], array['neglect']::text[], '6.5'),
  ('acquit', 'v', '/əˈkwɪt/', 'To formally declare someone not guilty.', 'The jury acquitted him for lack of evidence.', array['clear', 'exonerate']::text[], array['convict']::text[], '8.0'),
  ('delinquency', 'n', '/dɪˈlɪŋkwənsi/', 'Minor crime, especially by young people.', 'Youth clubs can reduce juvenile delinquency.', array['misconduct', 'wrongdoing']::text[], '{}'::text[], '8.0'),
  ('witness', 'n', '/ˈwɪtnəs/', 'A person who sees an event and can describe it.', 'A key witness changed her account in court.', array['observer', 'bystander']::text[], '{}'::text[], '6.5'),
  ('custody', 'n', '/ˈkʌstədi/', 'Imprisonment or protective care, especially before trial.', 'The suspect was held in custody overnight.', array['detention']::text[], array['release']::text[], '7.0'),
  ('perpetrator', 'n', '/ˈpɜːpətreɪtə/', 'A person who carries out a harmful or illegal act.', 'The perpetrators of the fraud were never caught.', array['offender', 'culprit']::text[], array['victim']::text[], '7.5'),
  ('legislation', 'n', '/ˌledʒɪsˈleɪʃn/', 'Laws considered collectively.', 'New legislation cracks down on online piracy.', array['law', 'statute']::text[], '{}'::text[], '7.0'),
  ('punitive', 'adj', '/ˈpjuːnətɪv/', 'Intended as punishment.', 'Punitive measures alone seldom change behaviour.', array['penal', 'disciplinary']::text[], array['rehabilitative']::text[], '8.0'),
  ('fraud', 'n', '/frɔːd/', 'Criminal deception for financial gain.', 'Online fraud has risen sharply in recent years.', array['deception', 'scam']::text[], array['honesty']::text[], '6.5'),
  ('parole', 'n', '/pəˈrəʊl/', 'The early release of a prisoner under conditions.', 'He was released on parole after serving half his sentence.', array['conditional release']::text[], '{}'::text[], '7.5'),
  ('liable', 'adj', '/ˈlaɪəbl/', 'Legally responsible for something.', 'Companies are liable for accidents caused by negligence.', array['responsible', 'accountable']::text[], array['exempt']::text[], '7.5'),
  ('abolish', 'v', '/əˈbɒlɪʃ/', 'To formally end a law, system or practice.', 'Many countries have abolished capital punishment.', array['scrap', 'repeal']::text[], array['establish', 'introduce']::text[], '7.0'),
  ('testimony', 'n', '/ˈtestɪməni/', 'A formal statement given in court.', 'Her testimony proved decisive at the trial.', array['evidence', 'statement']::text[], '{}'::text[], '7.5'),
  ('crackdown', 'n', '/ˈkrækdaʊn/', 'Severe action taken to control or stop something.', 'The government launched a crackdown on tax evasion.', array['clampdown', 'suppression']::text[], '{}'::text[], '7.0'),
  ('miscarriage of justice', 'phrase', '/mɪsˈkærɪdʒ əv ˈdʒʌstɪs/', 'A failure of a court to deliver a just outcome.', 'New DNA evidence revealed a shocking miscarriage of justice.', '{}'::text[], '{}'::text[], '8.0'),
  ('curb', 'v', '/kɜːb/', 'To restrain or keep something under control.', 'Tougher laws are needed to curb knife crime.', array['restrain', 'check']::text[], array['encourage']::text[], '7.5'),
  ('negligence', 'n', '/ˈneɡlɪdʒəns/', 'Failure to take proper care, causing harm.', 'The hospital was sued for medical negligence.', array['carelessness']::text[], array['diligence']::text[], '7.5'),
  ('law-abiding', 'adj', '/ˈlɔː əˌbaɪdɪŋ/', 'Obeying the law; respectable.', 'Most citizens are peaceful and law-abiding.', array['orderly', 'compliant']::text[], array['criminal']::text[], '7.0'),
  ('impunity', 'n', '/ɪmˈpjuːnəti/', 'Freedom from punishment or consequences.', 'Powerful figures seemed to act with complete impunity.', array['immunity']::text[], array['accountability']::text[], '8.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'crimeLaw'
on conflict (deck_id, word) do nothing;

-- ── Society & Culture (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('multicultural', 'adj', '/ˌmʌltiˈkʌltʃərəl/', 'Relating to several cultural groups within a society.', 'Modern cities are increasingly multicultural.', array['diverse', 'cosmopolitan']::text[], array['homogeneous']::text[], '7.0'),
  ('heritage', 'n', '/ˈherɪtɪdʒ/', 'Traditions and culture passed down through generations.', 'The festival celebrates the country’s rich cultural heritage.', array['legacy', 'tradition']::text[], '{}'::text[], '6.5'),
  ('integration', 'n', '/ˌɪntɪˈɡreɪʃn/', 'The process of mixing into a wider society.', 'Language classes aid the integration of newcomers.', array['assimilation', 'inclusion']::text[], array['segregation']::text[], '7.5'),
  ('norm', 'n', '/nɔːm/', 'An accepted standard of behaviour in a society.', 'Social norms vary enormously from culture to culture.', array['convention', 'standard']::text[], array['deviation']::text[], '7.0'),
  ('prejudice', 'n', '/ˈpredʒədɪs/', 'An unfair opinion formed without good reason.', 'Education is a powerful weapon against prejudice.', array['bias', 'bigotry']::text[], array['tolerance', 'fairness']::text[], '7.0'),
  ('cohesion', 'n', '/kəʊˈhiːʒn/', 'The state of forming a united, integrated whole.', 'Shared values strengthen social cohesion.', array['unity', 'solidarity']::text[], array['division']::text[], '7.5'),
  ('assimilate', 'v', '/əˈsɪməleɪt/', 'To absorb and integrate into a group or culture.', 'Second-generation immigrants often assimilate quickly.', array['integrate', 'absorb']::text[], array['alienate']::text[], '8.0'),
  ('stereotype', 'n', '/ˈsteriətaɪp/', 'A fixed, oversimplified idea about a group.', 'The film challenges tired national stereotypes.', array['cliché', 'generalisation']::text[], '{}'::text[], '7.0'),
  ('marginalised', 'adj', '/ˈmɑːdʒɪnəlaɪzd/', 'Treated as insignificant or pushed to the edge of society.', 'Policies often overlook the most marginalised groups.', array['excluded', 'sidelined']::text[], array['included']::text[], '8.0'),
  ('diversity', 'n', '/daɪˈvɜːsəti/', 'The state of being varied, especially of people.', 'Workplace diversity brings a wider range of ideas.', array['variety', 'plurality']::text[], array['uniformity']::text[], '6.5'),
  ('custom', 'n', '/ˈkʌstəm/', 'A traditional and widely accepted way of behaving.', 'Removing your shoes indoors is a long-standing custom there.', array['tradition', 'practice']::text[], '{}'::text[], '6.5'),
  ('conform', 'v', '/kənˈfɔːm/', 'To behave according to socially accepted standards.', 'Teenagers often feel pressure to conform to their peers.', array['comply', 'fit in']::text[], array['rebel', 'deviate']::text[], '7.0'),
  ('inequality', 'n', '/ˌɪnɪˈkwɒləti/', 'An unfair difference in status or opportunity.', 'Income inequality has widened over recent decades.', array['disparity', 'imbalance']::text[], array['equality']::text[], '7.0'),
  ('tolerance', 'n', '/ˈtɒlərəns/', 'Willingness to accept opinions or behaviour unlike one’s own.', 'A healthy democracy depends on mutual tolerance.', array['acceptance', 'open-mindedness']::text[], array['intolerance']::text[], '6.5'),
  ('indigenous', 'adj', '/ɪnˈdɪdʒənəs/', 'Originating naturally in a particular place; native.', 'Indigenous communities hold deep ecological knowledge.', array['native', 'aboriginal']::text[], array['foreign']::text[], '7.5'),
  ('ethnic', 'adj', '/ˈeθnɪk/', 'Relating to a group with a shared cultural tradition.', 'The country is home to dozens of ethnic minorities.', array['cultural']::text[], '{}'::text[], '6.5'),
  ('secular', 'adj', '/ˈsekjələ/', 'Not connected with religion or spiritual matters.', 'France maintains a strictly secular education system.', array['non-religious']::text[], array['religious']::text[], '8.0'),
  ('solidarity', 'n', '/ˌsɒlɪˈdærəti/', 'Unity arising from shared interests or feelings.', 'Workers marched in solidarity with the strikers.', array['unity', 'togetherness']::text[], array['discord']::text[], '7.5'),
  ('demographic', 'n', '/ˌdeməˈɡræfɪk/', 'A particular section of a population.', 'The product appeals to a younger demographic.', array['population group']::text[], '{}'::text[], '7.5'),
  ('taboo', 'n', '/təˈbuː/', 'A social or cultural prohibition on a topic or behaviour.', 'Discussing salaries remains a taboo in many cultures.', array['prohibition', 'ban']::text[], '{}'::text[], '7.5'),
  ('urbanisation', 'n', '/ˌɜːbənaɪˈzeɪʃn/', 'The increase in the proportion of people living in cities.', 'Rapid urbanisation has strained public services.', array['city growth']::text[], '{}'::text[], '7.0'),
  ('cohort', 'n', '/ˈkəʊhɔːt/', 'A group of people sharing a characteristic, often age.', 'This cohort grew up entirely with the internet.', array['generation', 'group']::text[], '{}'::text[], '8.0'),
  ('altruism', 'n', '/ˈæltruɪzəm/', 'Selfless concern for the welfare of others.', 'Volunteering is often driven by genuine altruism.', array['selflessness', 'generosity']::text[], array['selfishness']::text[], '8.5'),
  ('conservative', 'adj', '/kənˈsɜːvətɪv/', 'Reluctant to change; favouring tradition.', 'Older generations tend to hold more conservative views.', array['traditional', 'cautious']::text[], array['progressive', 'liberal']::text[], '7.0'),
  ('erode', 'v', '/ɪˈrəʊd/', 'To gradually destroy or weaken something.', 'Globalisation can erode local traditions.', array['weaken', 'undermine']::text[], array['strengthen']::text[], '7.5'),
  ('privileged', 'adj', '/ˈprɪvəlɪdʒd/', 'Having special advantages because of wealth or status.', 'Only a privileged few could afford university then.', array['advantaged', 'fortunate']::text[], array['disadvantaged']::text[], '7.0'),
  ('communal', 'adj', '/kəˈmjuːnl/', 'Shared by all members of a community.', 'The village shares a communal water supply.', array['shared', 'collective']::text[], array['private', 'individual']::text[], '7.5'),
  ('generation gap', 'phrase', '/ˌdʒenəˈreɪʃn ɡæp/', 'A difference in attitudes between younger and older people.', 'Technology has widened the generation gap in some families.', '{}'::text[], '{}'::text[], '6.5'),
  ('discrimination', 'n', '/dɪˌskrɪmɪˈneɪʃn/', 'Unfair treatment based on category such as race or sex.', 'Laws now prohibit discrimination in the workplace.', array['bias', 'prejudice']::text[], array['equality', 'fairness']::text[], '7.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'societyCulture'
on conflict (deck_id, word) do nothing;

-- ── Government & Globalisation (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('policy', 'n', '/ˈpɒləsi/', 'A course of action adopted by a government or organisation.', 'The new policy aims to cut child poverty in half.', array['strategy', 'plan']::text[], '{}'::text[], '6.5'),
  ('globalisation', 'n', '/ˌɡləʊbəlaɪˈzeɪʃn/', 'The process by which the world becomes more interconnected.', 'Globalisation has reshaped both trade and culture.', array['internationalisation']::text[], array['isolationism']::text[], '7.0'),
  ('democracy', 'n', '/dɪˈmɒkrəsi/', 'A system of government by the whole population through voting.', 'A free press is essential to a healthy democracy.', array['self-government']::text[], array['dictatorship']::text[], '6.5'),
  ('sovereignty', 'n', '/ˈsɒvrənti/', 'A nation’s authority to govern itself.', 'Some fear that trade deals erode national sovereignty.', array['autonomy', 'independence']::text[], array['dependence']::text[], '8.0'),
  ('legislation', 'n', '/ˌledʒɪsˈleɪʃn/', 'Laws collectively, or the process of making them.', 'Environmental legislation has tightened considerably.', array['law', 'statute']::text[], '{}'::text[], '7.0'),
  ('bureaucracy', 'n', '/bjʊəˈrɒkrəsi/', 'Complex administrative procedures and officials.', 'Excessive bureaucracy slows down even simple decisions.', array['red tape', 'administration']::text[], '{}'::text[], '7.5'),
  ('diplomacy', 'n', '/dɪˈpləʊməsi/', 'Managing international relations through negotiation.', 'The crisis was resolved through patient diplomacy.', array['negotiation', 'tact']::text[], array['hostility']::text[], '7.5'),
  ('accountability', 'n', '/əˌkaʊntəˈbɪləti/', 'The obligation to explain and take responsibility for actions.', 'Voters demand greater accountability from politicians.', array['responsibility', 'answerability']::text[], array['impunity']::text[], '7.5'),
  ('autonomy', 'n', '/ɔːˈtɒnəmi/', 'The right or condition of self-government.', 'The region was granted greater political autonomy.', array['independence', 'self-rule']::text[], array['dependence']::text[], '8.0'),
  ('referendum', 'n', '/ˌrefəˈrendəm/', 'A direct public vote on a single political question.', 'The constitution was changed by national referendum.', array['public vote', 'plebiscite']::text[], '{}'::text[], '7.5'),
  ('regulate', 'v', '/ˈreɡjuleɪt/', 'To control an activity by means of rules.', 'Governments are racing to regulate artificial intelligence.', array['control', 'govern']::text[], array['deregulate']::text[], '7.0'),
  ('welfare', 'n', '/ˈwelfeə/', 'Government support for those in need; well-being.', 'The welfare system protects the most vulnerable citizens.', array['benefits', 'social security']::text[], '{}'::text[], '6.5'),
  ('propaganda', 'n', '/ˌprɒpəˈɡændə/', 'Biased information used to promote a political cause.', 'State media flooded the country with propaganda.', array['misinformation', 'spin']::text[], '{}'::text[], '7.5'),
  ('advocate', 'v', '/ˈædvəkeɪt/', 'To publicly support or recommend something.', 'Many economists advocate higher taxes on carbon.', array['support', 'champion']::text[], array['oppose']::text[], '7.5'),
  ('interdependence', 'n', '/ˌɪntədɪˈpendəns/', 'A state of mutual reliance between parties.', 'Global trade has created deep economic interdependence.', array['mutual reliance']::text[], array['independence']::text[], '8.0'),
  ('austerity', 'n', '/ɔːˈsterəti/', 'Severe government measures to reduce spending.', 'Years of austerity left public services underfunded.', array['cutbacks', 'belt-tightening']::text[], array['stimulus']::text[], '8.0'),
  ('transparency', 'n', '/trænsˈpærənsi/', 'Openness and honesty in conducting affairs.', 'Citizens are calling for greater transparency in spending.', array['openness', 'candour']::text[], array['secrecy']::text[], '7.5'),
  ('sanction', 'n', '/ˈsæŋkʃn/', 'A penalty, often economic, imposed on a country.', 'International sanctions crippled the regime’s economy.', array['penalty', 'embargo']::text[], array['reward']::text[], '7.5'),
  ('governance', 'n', '/ˈɡʌvənəns/', 'The way in which an organisation or country is run.', 'Good governance attracts foreign investment.', array['administration', 'management']::text[], '{}'::text[], '8.0'),
  ('centralised', 'adj', '/ˈsentrəlaɪzd/', 'Controlled by a single central authority.', 'A heavily centralised system can ignore local needs.', array['concentrated']::text[], array['decentralised']::text[], '7.5'),
  ('mandate', 'n', '/ˈmændeɪt/', 'Authority to act, granted by an electorate.', 'The party claimed a clear mandate for reform.', array['authority', 'authorisation']::text[], '{}'::text[], '8.0'),
  ('repression', 'n', '/rɪˈpreʃn/', 'The use of force to control or subdue people.', 'The protests were met with brutal repression.', array['oppression', 'suppression']::text[], array['freedom']::text[], '7.5'),
  ('migration', 'n', '/maɪˈɡreɪʃn/', 'The movement of people from one place to another.', 'Economic migration reshapes both home and host countries.', array['movement', 'relocation']::text[], '{}'::text[], '6.5'),
  ('coalition', 'n', '/ˌkəʊəˈlɪʃn/', 'A temporary alliance, especially of political parties.', 'A fragile coalition formed after the election.', array['alliance', 'partnership']::text[], '{}'::text[], '7.5'),
  ('infrastructure', 'n', '/ˈɪnfrəstrʌktʃə/', 'Basic physical systems such as roads and power.', 'Investment in infrastructure boosts long-term growth.', array['facilities', 'framework']::text[], '{}'::text[], '7.0'),
  ('exploitation', 'n', '/ˌeksplɔɪˈteɪʃn/', 'Unfair use of people or resources for profit.', 'Critics highlight the exploitation of cheap overseas labour.', array['abuse', 'misuse']::text[], array['fair treatment']::text[], '7.5'),
  ('stability', 'n', '/stəˈbɪləti/', 'The state of being steady and not likely to change.', 'Political stability is vital for economic confidence.', array['steadiness', 'security']::text[], array['instability']::text[], '6.5'),
  ('protectionism', 'n', '/prəˈtekʃənɪzəm/', 'Shielding domestic industries through trade barriers.', 'Rising protectionism threatens global supply chains.', array['trade barriers']::text[], array['free trade']::text[], '8.5'),
  ('unify', 'v', '/ˈjuːnɪfaɪ/', 'To bring together to form a single unit.', 'A common currency was meant to unify the continent.', array['unite', 'merge']::text[], array['divide']::text[], '7.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'government'
on conflict (deck_id, word) do nothing;

-- ── Media & Advertising (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('influential', 'adj', '/ˌɪnfluˈenʃl/', 'Having great influence on people or events.', 'Social media stars are now hugely influential among teenagers.', array['powerful', 'persuasive']::text[], array['insignificant']::text[], '7.0'),
  ('sensationalism', 'n', '/senˈseɪʃənəlɪzəm/', 'Presenting news in a shocking way to attract attention.', 'Tabloid sensationalism distorts public understanding.', array['exaggeration']::text[], array['restraint']::text[], '8.0'),
  ('bias', 'n', '/ˈbaɪəs/', 'A tendency to favour one side unfairly.', 'Readers should be alert to political bias in reporting.', array['partiality', 'slant']::text[], array['objectivity']::text[], '7.0'),
  ('coverage', 'n', '/ˈkʌvərɪdʒ/', 'The reporting of an event by the media.', 'The election received round-the-clock news coverage.', array['reporting']::text[], '{}'::text[], '6.5'),
  ('manipulate', 'v', '/məˈnɪpjuleɪt/', 'To control or influence cleverly or unfairly.', 'Advertisers manipulate emotions to sell products.', array['exploit', 'influence']::text[], '{}'::text[], '7.5'),
  ('credible', 'adj', '/ˈkredəbl/', 'Able to be believed; convincing.', 'Always check whether a source is genuinely credible.', array['believable', 'reliable']::text[], array['dubious']::text[], '7.0'),
  ('misinformation', 'n', '/ˌmɪsɪnfəˈmeɪʃn/', 'False or inaccurate information, especially online.', 'Misinformation spreads faster than verified facts.', array['falsehood', 'fake news']::text[], array['truth']::text[], '7.5'),
  ('endorse', 'v', '/ɪnˈdɔːs/', 'To publicly declare approval or support, especially in ads.', 'Celebrities are paid to endorse beauty products.', array['back', 'promote']::text[], array['condemn']::text[], '7.5'),
  ('saturation', 'n', '/ˌsætʃəˈreɪʃn/', 'The point at which no more can be absorbed; oversupply.', 'Advertising saturation makes consumers tune out.', array['glut', 'overload']::text[], '{}'::text[], '8.0'),
  ('objective', 'adj', '/əbˈdʒektɪv/', 'Not influenced by personal feelings; unbiased.', 'Good journalism strives to be objective.', array['impartial', 'neutral']::text[], array['biased', 'subjective']::text[], '7.0'),
  ('persuasive', 'adj', '/pəˈsweɪsɪv/', 'Good at making people believe or do something.', 'The campaign’s persuasive imagery boosted sales.', array['convincing', 'compelling']::text[], array['unconvincing']::text[], '7.0'),
  ('scrutiny', 'n', '/ˈskruːtəni/', 'Close, critical examination.', 'Public figures live under constant media scrutiny.', array['examination', 'inspection']::text[], '{}'::text[], '7.5'),
  ('censorship', 'n', '/ˈsensəʃɪp/', 'The suppression of speech or media content.', 'Internet censorship limits access to independent news.', array['suppression', 'restriction']::text[], array['free speech']::text[], '7.5'),
  ('advertisement', 'n', '/ədˈvɜːtɪsmənt/', 'A notice or film promoting a product or service.', 'Children are exposed to thousands of advertisements a year.', array['advert', 'commercial']::text[], '{}'::text[], '6.5'),
  ('exposure', 'n', '/ɪkˈspəʊʒə/', 'The state of being seen or experienced widely.', 'Online platforms give small brands global exposure.', array['publicity', 'visibility']::text[], '{}'::text[], '7.0'),
  ('superficial', 'adj', '/ˌsuːpəˈfɪʃl/', 'Shallow; lacking depth or thoroughness.', 'Rolling news often gives only superficial analysis.', array['shallow', 'cursory']::text[], array['profound', 'thorough']::text[], '7.5'),
  ('viral', 'adj', '/ˈvaɪrəl/', 'Spreading rapidly and widely on the internet.', 'The clip went viral within hours of being posted.', array['widespread']::text[], '{}'::text[], '6.5'),
  ('distort', 'v', '/dɪˈstɔːt/', 'To give a misleading or false account of something.', 'Selective editing can distort what really happened.', array['misrepresent', 'twist']::text[], array['clarify']::text[], '7.5'),
  ('subscription', 'n', '/səbˈskrɪpʃn/', 'An arrangement to receive a service for regular payment.', 'Many newspapers now rely on digital subscriptions.', array['membership']::text[], '{}'::text[], '6.5'),
  ('propagate', 'v', '/ˈprɒpəɡeɪt/', 'To spread and promote an idea widely.', 'Rumours propagate quickly across messaging apps.', array['spread', 'disseminate']::text[], array['suppress']::text[], '8.0'),
  ('tabloid', 'n', '/ˈtæblɔɪd/', 'A popular newspaper focusing on sensational stories.', 'Tabloids prioritise celebrity gossip over hard news.', array['gutter press']::text[], array['broadsheet']::text[], '7.5'),
  ('consumerism', 'n', '/kənˈsjuːmərɪzəm/', 'A preoccupation with buying consumer goods.', 'Advertising fuels a culture of relentless consumerism.', array['materialism']::text[], '{}'::text[], '8.0'),
  ('accurate', 'adj', '/ˈækjərət/', 'Correct in all details; free from error.', 'Reporters have a duty to provide accurate information.', array['precise', 'correct']::text[], array['inaccurate']::text[], '6.5'),
  ('watchdog', 'n', '/ˈwɒtʃdɒɡ/', 'A person or group that monitors others’ conduct.', 'A media watchdog flagged the misleading advert.', array['monitor', 'regulator']::text[], '{}'::text[], '7.5'),
  ('stereotype', 'v', '/ˈsteriətaɪp/', 'To portray a group in a fixed, oversimplified way.', 'Adverts often stereotype men and women in outdated roles.', array['pigeonhole', 'typecast']::text[], '{}'::text[], '7.5'),
  ('hype', 'n', '/haɪp/', 'Intensive promotion that exaggerates importance.', 'The product never lived up to the marketing hype.', array['publicity', 'ballyhoo']::text[], '{}'::text[], '7.0'),
  ('intrusive', 'adj', '/ɪnˈtruːsɪv/', 'Disturbing privacy by entering where unwelcome.', 'Pop-up ads are widely seen as intrusive.', array['invasive', 'obtrusive']::text[], array['unobtrusive']::text[], '7.5'),
  ('disseminate', 'v', '/dɪˈsemɪneɪt/', 'To spread information widely.', 'The internet lets anyone disseminate news instantly.', array['circulate', 'broadcast']::text[], array['withhold']::text[], '8.5'),
  ('target audience', 'phrase', '/ˈtɑːɡɪt ˈɔːdiəns/', 'The specific group a product or message is aimed at.', 'The campaign was tailored to a teenage target audience.', '{}'::text[], '{}'::text[], '6.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'media'
on conflict (deck_id, word) do nothing;

-- ── Travel & Tourism (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('destination', 'n', '/ˌdestɪˈneɪʃn/', 'The place to which someone is travelling.', 'The island has become a top tourist destination.', array['place', 'resort']::text[], array['origin']::text[], '6.5'),
  ('itinerary', 'n', '/aɪˈtɪnərəri/', 'A planned route or schedule of a journey.', 'Our itinerary packed three cities into five days.', array['schedule', 'route']::text[], '{}'::text[], '7.0'),
  ('ecotourism', 'n', '/ˌiːkəʊˈtʊərɪzəm/', 'Responsible travel to natural areas that protects them.', 'Ecotourism funds the conservation of the rainforest.', array['green tourism']::text[], '{}'::text[], '7.5'),
  ('excursion', 'n', '/ɪkˈskɜːʃn/', 'A short trip, usually for pleasure.', 'The hotel offers daily excursions to nearby ruins.', array['outing', 'day trip']::text[], '{}'::text[], '7.0'),
  ('picturesque', 'adj', '/ˌpɪktʃəˈresk/', 'Visually attractive, especially in a quaint way.', 'We stayed in a picturesque fishing village.', array['scenic', 'charming']::text[], array['ugly', 'drab']::text[], '7.5'),
  ('hospitality', 'n', '/ˌhɒspɪˈtæləti/', 'Friendly, generous treatment of guests.', 'The region is famous for its warm hospitality.', array['friendliness', 'welcome']::text[], array['hostility']::text[], '7.0'),
  ('overcrowded', 'adj', '/ˌəʊvəˈkraʊdɪd/', 'Filled with too many people.', 'Famous landmarks are often unpleasantly overcrowded.', array['congested', 'packed']::text[], array['deserted']::text[], '6.5'),
  ('affordable', 'adj', '/əˈfɔːdəbl/', 'Reasonably priced; within one’s means.', 'Budget airlines have made travel far more affordable.', array['inexpensive', 'reasonable']::text[], array['expensive']::text[], '6.5'),
  ('exotic', 'adj', '/ɪɡˈzɒtɪk/', 'Strikingly unusual or foreign, especially in an exciting way.', 'Travellers increasingly seek out exotic destinations.', array['unusual', 'foreign']::text[], array['familiar', 'ordinary']::text[], '7.0'),
  ('accommodation', 'n', '/əˌkɒməˈdeɪʃn/', 'A place to stay, such as a hotel or rented room.', 'Affordable accommodation is scarce during festivals.', array['lodging', 'housing']::text[], '{}'::text[], '6.5'),
  ('venture', 'v', '/ˈventʃə/', 'To go somewhere despite possible risk.', 'Few tourists venture beyond the main resort.', array['dare', 'set out']::text[], '{}'::text[], '7.5'),
  ('scenic', 'adj', '/ˈsiːnɪk/', 'Providing attractive views of natural scenery.', 'We took the longer but more scenic coastal route.', array['picturesque', 'panoramic']::text[], array['drab']::text[], '7.0'),
  ('cosmopolitan', 'adj', '/ˌkɒzməˈpɒlɪtən/', 'Familiar with and comprising people from many cultures.', 'London is one of the world’s most cosmopolitan cities.', array['multicultural', 'worldly']::text[], array['provincial']::text[], '8.0'),
  ('landmark', 'n', '/ˈlændmɑːk/', 'A famous or easily recognised building or feature.', 'The tower is the city’s most photographed landmark.', array['monument', 'attraction']::text[], '{}'::text[], '6.5'),
  ('off the beaten track', 'phrase', '/ɒf ðə ˈbiːtn træk/', 'In a place far from where people usually go.', 'We prefer villages off the beaten track to busy resorts.', array['remote', 'secluded']::text[], '{}'::text[], '7.5'),
  ('wanderlust', 'n', '/ˈwɒndəlʌst/', 'A strong desire to travel and explore the world.', 'Her wanderlust took her to over forty countries.', array['travel bug']::text[], '{}'::text[], '8.0'),
  ('seasonal', 'adj', '/ˈsiːzənl/', 'Occurring or varying with the seasons.', 'Tourism here is highly seasonal, peaking in summer.', array['periodic']::text[], array['year-round']::text[], '7.0'),
  ('commercialised', 'adj', '/kəˈmɜːʃəlaɪzd/', 'Made too focused on making money, losing authenticity.', 'The once-quiet beach is now heavily commercialised.', array['exploited']::text[], array['unspoilt']::text[], '7.5'),
  ('immerse', 'v', '/ɪˈmɜːs/', 'To involve oneself deeply in an activity or environment.', 'Living abroad lets you immerse yourself in a new culture.', array['engross', 'absorb']::text[], '{}'::text[], '8.0'),
  ('breathtaking', 'adj', '/ˈbreθteɪkɪŋ/', 'Astonishing or awe-inspiring, especially in beauty.', 'The view from the summit was breathtaking.', array['stunning', 'spectacular']::text[], array['unremarkable']::text[], '7.0'),
  ('expedition', 'n', '/ˌekspəˈdɪʃn/', 'A journey undertaken for a particular purpose.', 'They joined an expedition to the polar ice cap.', array['journey', 'voyage']::text[], '{}'::text[], '7.0'),
  ('unspoilt', 'adj', '/ˌʌnˈspɔɪlt/', 'Not changed or damaged; still in a natural state.', 'The coastline remains remarkably unspoilt.', array['pristine', 'untouched']::text[], array['developed', 'spoilt']::text[], '7.5'),
  ('migrate', 'v', '/maɪˈɡreɪt/', 'To move from one region or habitat to another.', 'Some retirees migrate south for the warmer winters.', array['relocate', 'move']::text[], array['stay']::text[], '6.5'),
  ('vibrant', 'adj', '/ˈvaɪbrənt/', 'Full of energy, life and colour.', 'The market is a vibrant hub of local life.', array['lively', 'bustling']::text[], array['dull', 'lifeless']::text[], '7.0'),
  ('authentic', 'adj', '/ɔːˈθentɪk/', 'Genuine; truly representing its origins.', 'Tourists increasingly crave authentic local experiences.', array['genuine', 'real']::text[], array['fake', 'artificial']::text[], '7.0'),
  ('rejuvenate', 'v', '/rɪˈdʒuːvəneɪt/', 'To make someone feel younger and full of energy again.', 'A week by the sea rejuvenated the whole family.', array['refresh', 'revitalise']::text[], array['exhaust']::text[], '8.0'),
  ('remote', 'adj', '/rɪˈməʊt/', 'Far away from towns or other people; isolated.', 'The lodge sits in a remote mountain valley.', array['isolated', 'secluded']::text[], array['accessible', 'central']::text[], '6.5'),
  ('infrastructure', 'n', '/ˈɪnfrəstrʌktʃə/', 'Basic facilities such as transport and utilities.', 'Poor transport infrastructure deters foreign visitors.', array['facilities']::text[], '{}'::text[], '7.0'),
  ('bustling', 'adj', '/ˈbʌslɪŋ/', 'Full of energetic and noisy activity.', 'We wandered through the bustling night market.', array['busy', 'lively']::text[], array['quiet', 'sleepy']::text[], '7.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'travel'
on conflict (deck_id, word) do nothing;

-- ── Academic Word List (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('analyse', 'v', '/ˈænəlaɪz/', 'To examine something in detail to understand it.', 'The essay analyses the causes of urban poverty.', array['examine', 'study']::text[], '{}'::text[], '6.5'),
  ('significant', 'adj', '/sɪɡˈnɪfɪkənt/', 'Large or important enough to have an effect.', 'There has been a significant rise in living costs.', array['considerable', 'notable']::text[], array['negligible', 'minor']::text[], '6.5'),
  ('derive', 'v', '/dɪˈraɪv/', 'To obtain something from a source.', 'Much of our energy is still derived from coal.', array['obtain', 'gain']::text[], '{}'::text[], '7.0'),
  ('establish', 'v', '/ɪˈstæblɪʃ/', 'To set up or prove something firmly.', 'Researchers established a clear link between the two.', array['set up', 'demonstrate']::text[], array['abolish']::text[], '6.5'),
  ('evident', 'adj', '/ˈevɪdənt/', 'Clearly seen or understood; obvious.', 'It is evident that early intervention works best.', array['obvious', 'apparent']::text[], array['unclear']::text[], '7.0'),
  ('factor', 'n', '/ˈfæktə/', 'One element contributing to a result.', 'Cost is the decisive factor for most consumers.', array['element', 'cause']::text[], '{}'::text[], '6.5'),
  ('interpret', 'v', '/ɪnˈtɜːprɪt/', 'To explain the meaning of something.', 'The data can be interpreted in several ways.', array['explain', 'construe']::text[], array['misread']::text[], '7.0'),
  ('principle', 'n', '/ˈprɪnsəpl/', 'A fundamental truth or rule guiding behaviour.', 'The system rests on the principle of fairness.', array['rule', 'tenet']::text[], '{}'::text[], '7.0'),
  ('sufficient', 'adj', '/səˈfɪʃnt/', 'Enough for a particular purpose.', 'There is sufficient evidence to justify the policy.', array['adequate', 'ample']::text[], array['insufficient']::text[], '7.0'),
  ('consequently', 'adv', '/ˈkɒnsɪkwəntli/', 'As a result; therefore.', 'Demand fell and prices consequently dropped.', array['therefore', 'thus']::text[], '{}'::text[], '7.0'),
  ('framework', 'n', '/ˈfreɪmwɜːk/', 'A basic structure underlying a system or idea.', 'The treaty sets out a framework for cooperation.', array['structure', 'system']::text[], '{}'::text[], '7.5'),
  ('hypothesis', 'n', '/haɪˈpɒθəsɪs/', 'A proposed explanation tested by research.', 'The experiment supported the original hypothesis.', array['theory', 'proposition']::text[], '{}'::text[], '7.5'),
  ('phenomenon', 'n', '/fəˈnɒmɪnən/', 'A fact or situation that is observed to exist.', 'Mass migration is a global phenomenon.', array['occurrence', 'event']::text[], '{}'::text[], '7.5'),
  ('criteria', 'n', '/kraɪˈtɪəriə/', 'Standards by which something is judged.', 'Applicants are assessed against strict criteria.', array['standards', 'benchmarks']::text[], '{}'::text[], '7.0'),
  ('substantial', 'adj', '/səbˈstænʃl/', 'Large in amount, size or importance.', 'The charity received a substantial donation.', array['considerable', 'sizeable']::text[], array['minor', 'slight']::text[], '7.5'),
  ('underlying', 'adj', '/ˌʌndəˈlaɪɪŋ/', 'Existing beneath the surface; fundamental.', 'We must tackle the underlying causes of crime.', array['fundamental', 'root']::text[], array['superficial']::text[], '7.5'),
  ('advocate', 'n', '/ˈædvəkət/', 'A person who publicly supports a cause.', 'She is a leading advocate of renewable energy.', array['supporter', 'proponent']::text[], array['opponent']::text[], '7.5'),
  ('contradict', 'v', '/ˌkɒntrəˈdɪkt/', 'To assert the opposite; be inconsistent with.', 'These findings contradict earlier studies.', array['oppose', 'refute']::text[], array['confirm', 'support']::text[], '7.5'),
  ('notion', 'n', '/ˈnəʊʃn/', 'A belief, idea or concept.', 'The notion that money buys happiness is questionable.', array['idea', 'concept']::text[], '{}'::text[], '7.5'),
  ('attribute', 'v', '/əˈtrɪbjuːt/', 'To regard something as caused by a particular thing.', 'Experts attribute the decline to rising costs.', array['credit', 'ascribe']::text[], '{}'::text[], '7.5'),
  ('inevitable', 'adj', '/ɪnˈevɪtəbl/', 'Certain to happen; unavoidable.', 'Some job losses are an inevitable result of automation.', array['unavoidable', 'certain']::text[], array['avoidable']::text[], '7.5'),
  ('comprise', 'v', '/kəmˈpraɪz/', 'To consist of or be made up of.', 'The committee comprises experts from five countries.', array['consist of', 'constitute']::text[], '{}'::text[], '7.5'),
  ('correlation', 'n', '/ˌkɒrəˈleɪʃn/', 'A mutual relationship between two things.', 'There is a strong correlation between income and health.', array['connection', 'link']::text[], '{}'::text[], '8.0'),
  ('enhance', 'v', '/ɪnˈhɑːns/', 'To improve the quality or value of something.', 'Technology can greatly enhance the learning experience.', array['improve', 'boost']::text[], array['diminish', 'weaken']::text[], '7.0'),
  ('implication', 'n', '/ˌɪmplɪˈkeɪʃn/', 'A likely consequence or effect.', 'The ruling has serious implications for privacy.', array['consequence', 'ramification']::text[], '{}'::text[], '7.5'),
  ('validity', 'n', '/vəˈlɪdəti/', 'The quality of being logically sound or legally acceptable.', 'Critics questioned the validity of the survey.', array['soundness', 'legitimacy']::text[], array['invalidity']::text[], '8.0'),
  ('arbitrary', 'adj', '/ˈɑːbɪtrəri/', 'Based on random choice rather than reason.', 'The cut-off age seems entirely arbitrary.', array['random', 'capricious']::text[], array['reasoned', 'systematic']::text[], '8.0'),
  ('paradigm', 'n', '/ˈpærədaɪm/', 'A typical pattern or model of something.', 'Remote work has shifted the paradigm of office life.', array['model', 'pattern']::text[], '{}'::text[], '8.5'),
  ('cumulative', 'adj', '/ˈkjuːmjələtɪv/', 'Increasing by successive additions.', 'The cumulative effect of small savings is huge.', array['accumulating', 'collective']::text[], '{}'::text[], '8.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'awl'
on conflict (deck_id, word) do nothing;

-- ── Linkers & Cohesion (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('furthermore', 'adv', '/ˌfɜːðəˈmɔː/', 'In addition; used to add a supporting point.', 'The plan is costly; furthermore, it may not even work.', array['moreover', 'in addition']::text[], '{}'::text[], '7.0'),
  ('nevertheless', 'adv', '/ˌnevəðəˈles/', 'In spite of what has just been said.', 'The risks are real; nevertheless, the benefits outweigh them.', array['nonetheless', 'even so']::text[], '{}'::text[], '7.5'),
  ('consequently', 'adv', '/ˈkɒnsɪkwəntli/', 'As a result of something just mentioned.', 'Rents rose sharply and, consequently, many families moved.', array['therefore', 'as a result']::text[], '{}'::text[], '7.0'),
  ('conversely', 'adv', '/ˈkɒnvɜːsli/', 'Introducing a statement that reverses the previous one.', 'City life is convenient; conversely, it can be stressful.', array['on the other hand', 'in contrast']::text[], '{}'::text[], '8.0'),
  ('moreover', 'adv', '/mɔːrˈəʊvə/', 'Used to add information that strengthens a point.', 'The drug is expensive; moreover, it has side effects.', array['furthermore', 'besides']::text[], '{}'::text[], '7.0'),
  ('notably', 'adv', '/ˈnəʊtəbli/', 'Used to highlight an important example.', 'Several countries, notably Japan, face ageing populations.', array['particularly', 'especially']::text[], '{}'::text[], '7.5'),
  ('whereas', 'adv', '/weərˈæz/', 'In contrast or comparison with the fact that.', 'The north is industrial, whereas the south is agricultural.', array['while', 'in contrast']::text[], '{}'::text[], '7.0'),
  ('albeit', 'adv', '/ɔːlˈbiːɪt/', 'Although; even though (introducing a concession).', 'The reform succeeded, albeit at considerable cost.', array['although', 'even if']::text[], '{}'::text[], '8.0'),
  ('notwithstanding', 'adv', '/ˌnɒtwɪθˈstændɪŋ/', 'In spite of; nevertheless.', 'Notwithstanding the criticism, the policy continued.', array['despite', 'regardless']::text[], '{}'::text[], '8.5'),
  ('thereby', 'adv', '/ˌðeəˈbaɪ/', 'By that means; as a result of that.', 'Recycling reduces waste, thereby protecting resources.', array['thus', 'in that way']::text[], '{}'::text[], '8.0'),
  ('hence', 'adv', '/hens/', 'For this reason; therefore.', 'The data are incomplete; hence the cautious conclusion.', array['therefore', 'thus']::text[], '{}'::text[], '7.5'),
  ('for instance', 'phrase', '/fər ˈɪnstəns/', 'Used to introduce an example.', 'Many habits, for instance smoking, are hard to break.', array['for example', 'such as']::text[], '{}'::text[], '6.5'),
  ('in addition', 'phrase', '/ɪn əˈdɪʃn/', 'Used to add another point.', 'In addition, the scheme creates thousands of jobs.', array['furthermore', 'also']::text[], '{}'::text[], '6.5'),
  ('on the other hand', 'phrase', '/ɒn ðə ˈʌðə hænd/', 'Used to present a contrasting view.', 'On the other hand, some argue the opposite.', array['conversely', 'however']::text[], '{}'::text[], '6.5'),
  ('as a result', 'phrase', '/əz ə rɪˈzʌlt/', 'Because of something; consequently.', 'Sales fell and, as a result, staff were let go.', array['consequently', 'therefore']::text[], '{}'::text[], '6.5'),
  ('in contrast', 'phrase', '/ɪn ˈkɒntrɑːst/', 'Used to compare two opposing things.', 'In contrast, rural areas have lost population.', array['conversely', 'on the other hand']::text[], '{}'::text[], '7.0'),
  ('to illustrate', 'phrase', '/tu ˈɪləstreɪt/', 'Used to introduce a clarifying example.', 'To illustrate, consider the case of online banking.', array['for example', 'by way of example']::text[], '{}'::text[], '7.5'),
  ('by and large', 'phrase', '/baɪ ən lɑːdʒ/', 'On the whole; generally speaking.', 'By and large, the reforms have been welcomed.', array['generally', 'on the whole']::text[], '{}'::text[], '7.5'),
  ('owing to', 'phrase', '/ˈəʊɪŋ tu/', 'Because of; as a result of.', 'Owing to bad weather, the event was cancelled.', array['due to', 'because of']::text[], '{}'::text[], '7.0'),
  ('in essence', 'phrase', '/ɪn ˈesns/', 'Used to state the most basic point.', 'In essence, the argument boils down to fairness.', array['fundamentally', 'basically']::text[], '{}'::text[], '7.5'),
  ('all things considered', 'phrase', '/ɔːl θɪŋz kənˈsɪdəd/', 'After taking everything into account.', 'All things considered, the project was a success.', array['on balance', 'overall']::text[], '{}'::text[], '7.5'),
  ('granted that', 'phrase', '/ˈɡrɑːntɪd ðæt/', 'Used to admit a point before countering it.', 'Granted that costs are high, the long-term gains justify them.', array['admittedly', 'while it is true']::text[], '{}'::text[], '8.0'),
  ('in light of', 'phrase', '/ɪn laɪt əv/', 'Taking into account; because of.', 'In light of recent events, the rules were tightened.', array['considering', 'given']::text[], '{}'::text[], '7.5'),
  ('on balance', 'phrase', '/ɒn ˈbæləns/', 'After weighing all the factors.', 'On balance, the advantages outweigh the drawbacks.', array['overall', 'all things considered']::text[], '{}'::text[], '7.5'),
  ('to that end', 'phrase', '/tə ðæt end/', 'For that purpose; in order to achieve that.', 'The city wants cleaner air; to that end, it banned diesel cars.', array['for this reason', 'with this aim']::text[], '{}'::text[], '8.0'),
  ('despite this', 'phrase', '/dɪˈspaɪt ðɪs/', 'In spite of what was just mentioned.', 'The risks were clear; despite this, the plan went ahead.', array['nonetheless', 'even so']::text[], '{}'::text[], '7.0'),
  ('similarly', 'adv', '/ˈsɪmələli/', 'In a comparable way; likewise.', 'Cars pollute cities; similarly, factories foul rivers.', array['likewise', 'in the same way']::text[], '{}'::text[], '7.0'),
  ('ultimately', 'adv', '/ˈʌltɪmətli/', 'In the end; finally, after all considerations.', 'Ultimately, the decision rests with voters.', array['eventually', 'in the end']::text[], '{}'::text[], '7.0'),
  ('arguably', 'adv', '/ˈɑːɡjuəbli/', 'As can be argued or shown by reasoning.', 'It is arguably the most pressing issue of our age.', array['possibly', 'conceivably']::text[], '{}'::text[], '7.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'linkers'
on conflict (deck_id, word) do nothing;

-- ── High-band Collocations (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('pose a threat', 'phrase', '', 'To be a danger to someone or something.', 'Rising sea levels pose a serious threat to coastal cities.', array['endanger', 'jeopardise']::text[], '{}'::text[], '7.0'),
  ('play a pivotal role', 'phrase', '', 'To be extremely important in a process or outcome.', 'Education plays a pivotal role in reducing poverty.', array['be crucial', 'be central']::text[], '{}'::text[], '7.5'),
  ('a vested interest', 'phrase', '', 'A personal stake in something, often financial.', 'Oil firms have a vested interest in delaying reform.', array['a stake', 'self-interest']::text[], '{}'::text[], '8.0'),
  ('bridge the gap', 'phrase', '', 'To reduce or remove a difference between things.', 'Scholarships help bridge the gap between rich and poor students.', array['close the gap']::text[], array['widen the gap']::text[], '7.5'),
  ('a viable alternative', 'phrase', '', 'A realistic and workable option.', 'Solar power is now a viable alternative to coal.', array['a feasible option']::text[], '{}'::text[], '7.5'),
  ('far-reaching consequences', 'phrase', '', 'Effects that are extensive and long-lasting.', 'The decision had far-reaching consequences for the economy.', array['wide-ranging effects']::text[], '{}'::text[], '7.5'),
  ('a contentious issue', 'phrase', '', 'A subject that causes a lot of disagreement.', 'Immigration remains a contentious issue in many countries.', array['a divisive topic']::text[], '{}'::text[], '8.0'),
  ('strike a balance', 'phrase', '', 'To find a sensible compromise between two things.', 'Parents must strike a balance between freedom and control.', array['find a compromise']::text[], '{}'::text[], '7.5'),
  ('raise awareness', 'phrase', '', 'To increase public knowledge of an issue.', 'The campaign aims to raise awareness of recycling.', array['highlight', 'publicise']::text[], '{}'::text[], '7.0'),
  ('deep-rooted', 'adj', '/ˌdiːp ˈruːtɪd/', 'Firmly established and hard to change.', 'Many social problems are deep-rooted and complex.', array['ingrained', 'entrenched']::text[], array['superficial']::text[], '7.5'),
  ('widely acknowledged', 'phrase', '', 'Generally accepted or recognised by most people.', 'It is widely acknowledged that exercise improves mood.', array['generally accepted']::text[], array['disputed']::text[], '7.5'),
  ('a pressing concern', 'phrase', '', 'An issue that needs urgent attention.', 'Youth unemployment is a pressing concern for the government.', array['an urgent issue']::text[], '{}'::text[], '7.5'),
  ('gain momentum', 'phrase', '', 'To grow stronger or faster over time.', 'The campaign for cleaner energy is gaining momentum.', array['build up', 'accelerate']::text[], array['lose momentum']::text[], '7.5'),
  ('shed light on', 'phrase', '', 'To make something easier to understand.', 'The study sheds light on why teenagers sleep poorly.', array['clarify', 'illuminate']::text[], array['obscure']::text[], '8.0'),
  ('take its toll', 'phrase', '', 'To cause gradual harm or damage.', 'Long working hours take their toll on family life.', array['have a negative effect']::text[], '{}'::text[], '7.5'),
  ('a double-edged sword', 'phrase', '', 'Something with both good and bad consequences.', 'Tourism is a double-edged sword for fragile regions.', array['a mixed blessing']::text[], '{}'::text[], '8.0'),
  ('address the issue', 'phrase', '', 'To deal with or tackle a problem.', 'Governments must address the issue of plastic waste.', array['tackle', 'confront']::text[], array['ignore']::text[], '7.0'),
  ('a knock-on effect', 'phrase', '', 'A secondary effect caused by an initial event.', 'Fuel price rises have a knock-on effect on food costs.', array['ripple effect', 'chain reaction']::text[], '{}'::text[], '7.5'),
  ('a last resort', 'phrase', '', 'A final option when all else has failed.', 'Surgery is considered only as a last resort.', array['final option']::text[], '{}'::text[], '7.0'),
  ('detrimental impact', 'phrase', '', 'A harmful effect on something.', 'Pollution has a detrimental impact on public health.', array['harmful effect']::text[], array['beneficial impact']::text[], '7.5'),
  ('a sedentary lifestyle', 'phrase', '', 'A way of living with very little physical activity.', 'A sedentary lifestyle contributes to many illnesses.', '{}'::text[], array['an active lifestyle']::text[], '7.5'),
  ('vast majority', 'phrase', '', 'Almost all of a group.', 'The vast majority of commuters favour cleaner transport.', array['overwhelming majority']::text[], array['tiny minority']::text[], '7.0'),
  ('heavily reliant', 'phrase', '', 'Depending very much on something.', 'The economy is heavily reliant on tourism.', array['dependent on']::text[], array['independent of']::text[], '7.5'),
  ('a stark contrast', 'phrase', '', 'A very obvious and striking difference.', 'There is a stark contrast between urban and rural incomes.', array['sharp difference']::text[], array['similarity']::text[], '7.5'),
  ('fall short of', 'phrase', '', 'To fail to reach a required standard.', 'The results fell short of expectations.', array['fail to meet']::text[], array['exceed']::text[], '7.5'),
  ('unprecedented levels', 'phrase', '', 'Amounts never seen or reached before.', 'House prices have reached unprecedented levels.', array['record levels']::text[], '{}'::text[], '8.0'),
  ('curb the rise', 'phrase', '', 'To restrain or limit an increase.', 'New taxes are intended to curb the rise in emissions.', array['limit the increase']::text[], '{}'::text[], '8.0'),
  ('reap the benefits', 'phrase', '', 'To enjoy the rewards of an effort.', 'Students who study consistently reap the benefits later.', array['enjoy the rewards']::text[], '{}'::text[], '7.5'),
  ('a growing tendency', 'phrase', '', 'An increasing inclination toward something.', 'There is a growing tendency to work from home.', array['an increasing trend']::text[], '{}'::text[], '7.5')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'collocations'
on conflict (deck_id, word) do nothing;

-- ── Speaking · Part 3 & Idioms (29) ──
insert into vocabulary_words (deck_id, word, part_of_speech, ipa, definition, example, synonyms, antonyms, band_level)
select d.id, w.word, w.pos, w.ipa, w.def, w.ex, w.syn, w.ant, w.band
from vocabulary_decks d
cross join (values
  ('off the top of my head', 'phrase', '', 'Without taking time to check or think carefully.', 'Off the top of my head, I’d say about ten.', array['without thinking']::text[], '{}'::text[], '7.5'),
  ('in the long run', 'phrase', '', 'Over an extended period in the future.', 'Studying abroad pays off in the long run.', array['eventually', 'ultimately']::text[], array['in the short term']::text[], '7.0'),
  ('a blessing in disguise', 'phrase', '', 'A misfortune that turns out to have benefits.', 'Losing that job was a blessing in disguise.', array['a silver lining']::text[], '{}'::text[], '7.5'),
  ('when it comes to', 'phrase', '', 'Used to introduce a particular topic.', 'When it comes to cooking, I’m pretty hopeless.', array['regarding', 'as for']::text[], '{}'::text[], '6.5'),
  ('more often than not', 'phrase', '', 'Usually; in most cases.', 'More often than not, I walk to work.', array['usually', 'generally']::text[], array['rarely']::text[], '7.0'),
  ('the bigger picture', 'phrase', '', 'The most important facts about a situation.', 'It helps to step back and see the bigger picture.', array['the wider view']::text[], array['the details']::text[], '7.5'),
  ('food for thought', 'phrase', '', 'Something worth thinking about seriously.', 'That documentary really gave me food for thought.', array['something to ponder']::text[], '{}'::text[], '7.5'),
  ('see eye to eye', 'phrase', '', 'To agree completely with someone.', 'My brother and I don’t always see eye to eye.', array['agree']::text[], array['disagree']::text[], '7.5'),
  ('hit the nail on the head', 'phrase', '', 'To describe exactly what is causing a situation.', 'You’ve hit the nail on the head with that point.', array['be exactly right']::text[], '{}'::text[], '8.0'),
  ('a grey area', 'phrase', '', 'A situation where the rules are unclear.', 'Online privacy is still a bit of a grey area.', array['ambiguous area']::text[], '{}'::text[], '7.5'),
  ('to be honest', 'phrase', '', 'Used to introduce a frank opinion.', 'To be honest, I’ve never really enjoyed sport.', array['frankly', 'honestly']::text[], '{}'::text[], '6.5'),
  ('take it for granted', 'phrase', '', 'To assume something without appreciating it.', 'We often take clean water for granted.', array['assume', 'undervalue']::text[], array['appreciate']::text[], '7.5'),
  ('a means to an end', 'phrase', '', 'Something done only to achieve a result, not for itself.', 'For me, the job is just a means to an end.', '{}'::text[], '{}'::text[], '7.5'),
  ('get the hang of', 'phrase', '', 'To learn how to do something with practice.', 'It took me a week to get the hang of the software.', array['master', 'learn']::text[], '{}'::text[], '7.0'),
  ('be torn between', 'phrase', '', 'To be unable to choose between two options.', 'I’m torn between studying medicine and law.', array['be undecided']::text[], '{}'::text[], '7.5'),
  ('without a doubt', 'phrase', '', 'Used to express complete certainty.', 'Without a doubt, it’s the best city I’ve visited.', array['definitely', 'certainly']::text[], '{}'::text[], '7.0'),
  ('broaden your horizons', 'phrase', '', 'To widen the range of your knowledge or experience.', 'Travelling really broadens your horizons.', array['expand your outlook']::text[], '{}'::text[], '8.0'),
  ('have mixed feelings', 'phrase', '', 'To feel both positive and negative about something.', 'I have mixed feelings about social media.', array['be ambivalent']::text[], '{}'::text[], '7.0'),
  ('a far cry from', 'phrase', '', 'Very different from something.', 'City life is a far cry from the village I grew up in.', array['very different from']::text[], '{}'::text[], '8.0'),
  ('can’t stand', 'phrase', '', 'To strongly dislike something.', 'I can’t stand being stuck in traffic.', array['detest', 'loathe']::text[], array['love']::text[], '6.5'),
  ('keep up with', 'phrase', '', 'To stay informed about or level with something.', 'It’s hard to keep up with the latest technology.', array['stay current']::text[], array['fall behind']::text[], '7.0'),
  ('for the most part', 'phrase', '', 'Mostly; in most respects.', 'For the most part, people here are very friendly.', array['mostly', 'largely']::text[], '{}'::text[], '7.0'),
  ('a once-in-a-lifetime opportunity', 'phrase', '', 'A chance that is unlikely to come again.', 'Studying there was a once-in-a-lifetime opportunity.', array['a rare chance']::text[], '{}'::text[], '7.5'),
  ('put it into perspective', 'phrase', '', 'To compare something so its real importance is clear.', 'Travelling abroad put my own problems into perspective.', array['see it clearly']::text[], '{}'::text[], '8.0'),
  ('a double standard', 'phrase', '', 'A rule applied unfairly to different people.', 'There’s a double standard in how the two are judged.', array['unfairness', 'hypocrisy']::text[], '{}'::text[], '8.0'),
  ('second to none', 'phrase', '', 'Better than anything else of the same kind.', 'The country’s public transport is second to none.', array['unrivalled', 'the best']::text[], '{}'::text[], '8.0'),
  ('cut corners', 'phrase', '', 'To do something cheaply or quickly, often poorly.', 'Builders who cut corners put safety at risk.', array['skimp']::text[], '{}'::text[], '7.5'),
  ('the be-all and end-all', 'phrase', '', 'The most important element; the only thing that matters.', 'For some students, grades are the be-all and end-all.', array['the most important thing']::text[], '{}'::text[], '8.5'),
  ('get to grips with', 'phrase', '', 'To begin to understand and deal with something difficult.', 'It took time to get to grips with living alone.', array['come to terms with']::text[], '{}'::text[], '8.0')
) as w(word, pos, ipa, def, ex, syn, ant, band)
where d.slug = 'speakingIdioms'
on conflict (deck_id, word) do nothing;

-- Total words: 406 across 14 decks